import { chromium } from "playwright";
const b = await chromium.launch({ args:["--use-angle=d3d11","--ignore-gpu-blocklist"] });
const ctx = await b.newContext({ viewport:{width:412,height:900}, deviceScaleFactor:2, isMobile:true, hasTouch:true });
const p = await ctx.newPage();
const errs=[]; p.on("console",m=>{if(m.type()==="error")errs.push(m.text())}); p.on("pageerror",e=>errs.push("PE:"+e.message));
await p.goto("http://localhost:4335/atlas/",{waitUntil:"networkidle"}); await p.waitForTimeout(700);
await p.click("#at-intro-go").catch(()=>{}); await p.waitForSelector("#atlas.live",{timeout:20000}).catch(()=>{}); await p.waitForTimeout(7000);
await p.evaluate(()=>window.__atlasGalView && window.__atlasGalView());
await p.waitForTimeout(8000);
await p.screenshot({path:"C:/Users/devan/celestium/.shots/galaxy-mobile.png"});
const fps=await p.evaluate(()=>new Promise(r=>{let n=0,t=performance.now();(function f(){n++;performance.now()-t<2500?requestAnimationFrame(f):r(Math.round(n/((performance.now()-t)/1000)))})()}));
console.log("MOBILE FPS:",fps,"| errors:",errs.length?errs.slice(0,5):"none");
await b.close();
