/* CELESTIUM — EXOPLANET SYSTEMS (data). 80 real systems at their
   true J2000 sky positions. Physical truth (radii, masses, orbits, periods,
   temperatures) from the per-system scientific model packs (NASA Exoplanet
   Archive pscomppars); sky position (RA/Dec) + distance + spectral type from the
   same archive. Star colour derived from effective temperature (blackbody).
   GENERATED by scripts/build-exo.mjs — edit the packs/script, not this file. */
export interface ExoPlanet { key: string; name: string; rE: number; au: number; per: number; kind: string; massE: number | null; tempK: number | null; }
export interface ExoSystem { pack: string; star: string; ra: number; dec: number; ly: number; tempK: number | null; spec: string; rSun: number; col: number; pulsar: boolean; kindStar: string; pbr?: boolean; planets: ExoPlanet[]; }
const EXO_SYSTEMS: ExoSystem[] = [
 {
  "pack": "Kepler-452",
  "star": "Kepler-452",
  "ra": 19.7442,
  "dec": 44.278,
  "ly": 1810,
  "tempK": 5578,
  "spec": "",
  "rSun": 0.793,
  "col": 16773846,
  "pulsar": false,
  "kindStar": "K-type main-sequence star",
  "planets": [
   {
    "key": "b",
    "name": "Kepler-452 b",
    "rE": 1.13,
    "au": 0.9892,
    "per": 384.84,
    "kind": "cold rocky planet",
    "massE": null,
    "tempK": 220
   }
  ],
  "pbr": false
 },
 {
  "pack": "Fomalhaut",
  "star": "Fomalhaut",
  "ra": 22.9608,
  "dec": -29.622,
  "ly": 25.1,
  "tempK": 8590,
  "spec": "A3 V",
  "rSun": 1.829,
  "col": 15265535,
  "pulsar": false,
  "kindStar": "A-type main-sequence star",
  "planets": [
   {
    "key": "b",
    "name": "Fomalhaut b",
    "rE": 5.5,
    "au": 115,
    "per": 874666,
    "kind": "gas giant / directly imaged planet",
    "massE": 1000,
    "tempK": 290
   }
  ],
  "pbr": false
 },
 {
  "pack": "Upsilon_Andromedae",
  "star": "ups And",
  "ra": 1.6171,
  "dec": 41.406,
  "ly": 44,
  "tempK": 6200,
  "spec": "F8 V",
  "rSun": 1.25,
  "col": 16774378,
  "pulsar": false,
  "kindStar": "F-type main-sequence star",
  "planets": [
   {
    "key": "b",
    "name": "ups And b",
    "rE": 11,
    "au": 0.057,
    "per": 4.61,
    "kind": "gas giant",
    "massE": 216.1244,
    "tempK": null
   },
   {
    "key": "c",
    "name": "ups And c",
    "rE": 11,
    "au": 0.821,
    "per": 238.1,
    "kind": "gas giant",
    "massE": 715.09,
    "tempK": null
   },
   {
    "key": "d",
    "name": "ups And d",
    "rE": 11,
    "au": 2.51,
    "per": 1274.6,
    "kind": "gas giant",
    "massE": 1255.38,
    "tempK": null
   }
  ],
  "pbr": false
 },
 {
  "pack": "KELT-9",
  "star": "KELT-9",
  "ra": 20.5161,
  "dec": 39.956,
  "ly": 670,
  "tempK": 10170,
  "spec": "B9.5-A0",
  "rSun": 2.36,
  "col": 11193599,
  "pulsar": false,
  "kindStar": "B-type main-sequence star",
  "planets": [
   {
    "key": "b",
    "name": "KELT-9 b",
    "rE": 21.2,
    "au": 0.0346,
    "per": 1.48,
    "kind": "gas giant",
    "massE": 915.3504,
    "tempK": 4050
   }
  ],
  "pbr": false
 },
 {
  "pack": "PSR_B1257+12",
  "star": "PSR B1257+12",
  "ra": 13.0058,
  "dec": 12.683,
  "ly": 1955,
  "tempK": null,
  "spec": "",
  "rSun": 0.85,
  "col": 16773846,
  "pulsar": true,
  "kindStar": "main-sequence star",
  "planets": [
   {
    "key": "b",
    "name": "PSR B1257+12 b",
    "rE": 0.32,
    "au": 0.19,
    "per": 25.34,
    "kind": "pulsar-orbiting rocky planet",
    "massE": 0.015,
    "tempK": null
   },
   {
    "key": "c",
    "name": "PSR B1257+12 c",
    "rE": 1.39,
    "au": 0.36,
    "per": 66.56,
    "kind": "pulsar-orbiting rocky planet",
    "massE": 3.4,
    "tempK": null
   },
   {
    "key": "d",
    "name": "PSR B1257+12 d",
    "rE": 1.44,
    "au": 0.46,
    "per": 98.21,
    "kind": "pulsar-orbiting rocky planet",
    "massE": 3.9,
    "tempK": null
   }
  ],
  "pbr": false
 },
 {
  "pack": "47_Ursae_Majoris",
  "star": "47 UMa",
  "ra": 10.953,
  "dec": 40.431,
  "ly": 45.9,
  "tempK": 5829.16,
  "spec": "",
  "rSun": 1.135,
  "col": 16773846,
  "pulsar": false,
  "kindStar": "K-type main-sequence star",
  "planets": [
   {
    "key": "b",
    "name": "47 UMa b",
    "rE": 11,
    "au": 2.059,
    "per": 1076.6,
    "kind": "gas giant",
    "massE": 774.86565627,
    "tempK": null
   },
   {
    "key": "c",
    "name": "47 UMa c",
    "rE": 11,
    "au": 3.404,
    "per": 2287,
    "kind": "gas giant",
    "massE": 157.96071828,
    "tempK": null
   },
   {
    "key": "d",
    "name": "47 UMa d",
    "rE": 11,
    "au": 11.6,
    "per": 14002,
    "kind": "gas giant",
    "massE": 521.22,
    "tempK": null
   }
  ],
  "pbr": false
 },
 {
  "pack": "51_Peg",
  "star": "51 Pegasi",
  "ra": 22.9578,
  "dec": 20.7691,
  "ly": 50.428,
  "tempK": 5758,
  "spec": "G5V",
  "rSun": 1.176,
  "col": 16773862,
  "pulsar": false,
  "kindStar": "Sun-like G-type star (main sequence)",
  "pbr": true,
  "planets": [
   {
    "key": "b",
    "name": "51 Peg b",
    "rE": 14.3,
    "au": 0.0527,
    "per": 4.2308,
    "kind": "gas giant",
    "massE": 146.202,
    "tempK": 1311
   }
  ]
 },
 {
  "pack": "55_Cnc",
  "star": "55 Cancri",
  "ra": 8.8765,
  "dec": 28.3298,
  "ly": 41.048,
  "tempK": 5172,
  "spec": "G8 V",
  "rSun": 0.943,
  "col": 16771028,
  "pulsar": false,
  "kindStar": "Sun-like G-type star (main sequence)",
  "pbr": true,
  "planets": [
   {
    "key": "e",
    "name": "55 Cnc e",
    "rE": 1.875,
    "au": 0.01544,
    "per": 0.7365,
    "kind": "ultra-hot rocky super-earth",
    "massE": 7.99,
    "tempK": 1958
   },
   {
    "key": "b",
    "name": "55 Cnc b",
    "rE": 13.9,
    "au": 0.118,
    "per": 14.6516,
    "kind": "gas giant",
    "massE": 263.978,
    "tempK": 700
   },
   {
    "key": "c",
    "name": "55 Cnc c",
    "rE": 8.51,
    "au": 0.247,
    "per": 44.3936,
    "kind": "gas giant",
    "massE": 54.474,
    "tempK": 499
   },
   {
    "key": "f",
    "name": "55 Cnc f",
    "rE": 7.59,
    "au": 0.802,
    "per": 260.58,
    "kind": "super-earth",
    "massE": 44.812,
    "tempK": 277
   },
   {
    "key": "d",
    "name": "55 Cnc d",
    "rE": 13,
    "au": 5.6,
    "per": 4799,
    "kind": "gas giant",
    "massE": 1232.493,
    "tempK": 105
   }
  ]
 },
 {
  "pack": "AU_Mic",
  "star": "AU Microscopii",
  "ra": 20.7527,
  "dec": -31.3424,
  "ly": 31.709,
  "tempK": 3540,
  "spec": "M1 V",
  "rSun": 0.862,
  "col": 16761487,
  "pulsar": false,
  "kindStar": "red-dwarf star (main sequence)",
  "pbr": true,
  "planets": [
   {
    "key": "b",
    "name": "AU Mic b",
    "rE": 4.79,
    "au": 0.07,
    "per": 8.4634,
    "kind": "super-earth",
    "massE": 8.99,
    "tempK": 555
   },
   {
    "key": "c",
    "name": "AU Mic c",
    "rE": 2.79,
    "au": 0.119,
    "per": 18.859,
    "kind": "super-earth",
    "massE": 14.46,
    "tempK": 425
   },
   {
    "key": "d",
    "name": "AU Mic d",
    "rE": 1.02,
    "au": 0.05,
    "per": 12.736,
    "kind": "rocky terrestrial or super-earth candidate",
    "massE": 1.053,
    "tempK": null
   }
  ]
 },
 {
  "pack": "Barnard_s_star",
  "star": "Barnard's Star",
  "ra": 17.9632,
  "dec": 4.738,
  "ly": 5.957,
  "tempK": 3195,
  "spec": "M3.5-4 V",
  "rSun": 0.185,
  "col": 16758651,
  "pulsar": false,
  "kindStar": "red-dwarf star (main sequence)",
  "pbr": true,
  "planets": [
   {
    "key": "d",
    "name": "Barnard d",
    "rE": 0.694,
    "au": 0.0188,
    "per": 2.3402,
    "kind": "rocky terrestrial or super-earth candidate",
    "massE": 0.263,
    "tempK": 483
   },
   {
    "key": "b",
    "name": "Barnard b",
    "rE": 0.72,
    "au": 0.0229,
    "per": 3.1542,
    "kind": "rocky terrestrial or super-earth candidate",
    "massE": 0.299,
    "tempK": 438
   },
   {
    "key": "c",
    "name": "Barnard c",
    "rE": 0.743,
    "au": 0.0274,
    "per": 4.1244,
    "kind": "rocky terrestrial or super-earth candidate",
    "massE": 0.335,
    "tempK": 400
   },
   {
    "key": "e",
    "name": "Barnard e",
    "rE": 0.637,
    "au": 0.0381,
    "per": 6.7392,
    "kind": "rocky terrestrial or super-earth candidate",
    "massE": 0.193,
    "tempK": 340
   }
  ]
 },
 {
  "pack": "bet_Pic",
  "star": "Beta Pictoris",
  "ra": 5.7881,
  "dec": -51.0661,
  "ly": 64.397,
  "tempK": 8039,
  "spec": "A5V",
  "rSun": 1.544,
  "col": 14542335,
  "pulsar": false,
  "kindStar": "white A-type star (main sequence)",
  "pbr": true,
  "planets": [
   {
    "key": "c",
    "name": "bet Pic c",
    "rE": 12.5,
    "au": 2.68,
    "per": 1192.7795,
    "kind": "gas giant",
    "massE": 3222.462,
    "tempK": 1250
   },
   {
    "key": "b",
    "name": "bet Pic b",
    "rE": 18.495,
    "au": 10.018,
    "per": 8617.5095,
    "kind": "gas giant",
    "massE": 3727.809,
    "tempK": 1612
   }
  ]
 },
 {
  "pack": "GJ_1132",
  "star": "GJ 1132",
  "ra": 10.2473,
  "dec": -47.1549,
  "ly": 41.138,
  "tempK": 3229,
  "spec": "M4.5 V",
  "rSun": 0.221,
  "col": 16759165,
  "pulsar": false,
  "kindStar": "red-dwarf star (main sequence)",
  "pbr": true,
  "planets": [
   {
    "key": "b",
    "name": "GJ 1132 b",
    "rE": 1.192,
    "au": 0.0157,
    "per": 1.6289,
    "kind": "hot rocky transiting terrestrial planet",
    "massE": 1.837,
    "tempK": 584
   },
   {
    "key": "c",
    "name": "GJ 1132 c",
    "rE": 1.52,
    "au": 0.0476,
    "per": 8.929,
    "kind": "warm",
    "massE": 2.91,
    "tempK": 300
   }
  ]
 },
 {
  "pack": "GJ_1214",
  "star": "GJ 1214",
  "ra": 17.2554,
  "dec": 4.9607,
  "ly": 47.758,
  "tempK": 3101,
  "spec": "M4 V",
  "rSun": 0.216,
  "col": 16757877,
  "pulsar": false,
  "kindStar": "red-dwarf star (main sequence)",
  "pbr": true,
  "planets": [
   {
    "key": "b",
    "name": "GJ 1214 b",
    "rE": 2.733,
    "au": 0.01505,
    "per": 1.5804,
    "kind": "super-earth",
    "massE": 8.41,
    "tempK": 567
   }
  ]
 },
 {
  "pack": "GJ_180",
  "star": "GJ 180",
  "ra": 4.8973,
  "dec": -17.7762,
  "ly": 38.945,
  "tempK": 3371,
  "spec": "M3",
  "rSun": 0.413,
  "col": 16760197,
  "pulsar": false,
  "kindStar": "red-dwarf star",
  "pbr": true,
  "planets": [
   {
    "key": "b",
    "name": "GJ 180 b",
    "rE": 2.43,
    "au": 0.092,
    "per": 17.133,
    "kind": "volatile-rich sub-neptune",
    "massE": 6.49,
    "tempK": 344
   },
   {
    "key": "c",
    "name": "GJ 180 c",
    "rE": 2.41,
    "au": 0.129,
    "per": 24.329,
    "kind": "volatile-rich sub-neptune",
    "massE": 6.4,
    "tempK": 291
   },
   {
    "key": "d",
    "name": "GJ 180 d",
    "rE": 2.66,
    "au": 0.309,
    "per": 106.3,
    "kind": "cold volatile-rich mini-neptune",
    "massE": 7.56,
    "tempK": 188
   }
  ]
 },
 {
  "pack": "GJ_3090",
  "star": "GJ 3090",
  "ra": 1.3626,
  "dec": -46.7147,
  "ly": 73.304,
  "tempK": 3707,
  "spec": "M2 V",
  "rSun": 0.516,
  "col": 16762520,
  "pulsar": false,
  "kindStar": "red-dwarf star (main sequence)",
  "pbr": true,
  "planets": [
   {
    "key": "b",
    "name": "GJ 3090 b",
    "rE": 2.18,
    "au": 0.0316,
    "per": 2.8531,
    "kind": "hot",
    "massE": 4.52,
    "tempK": 723
   },
   {
    "key": "c",
    "name": "GJ 3090 c",
    "rE": 3.14,
    "au": 0.0997,
    "per": 15.9407,
    "kind": "warm volatile-rich sub-neptune",
    "massE": 10,
    "tempK": 407
   }
  ]
 },
 {
  "pack": "GJ_3323",
  "star": "GJ 3323",
  "ra": 5.0325,
  "dec": -6.9485,
  "ly": 17.53,
  "tempK": 3159,
  "spec": "M4",
  "rSun": 0.119,
  "col": 16758393,
  "pulsar": false,
  "kindStar": "red-dwarf star",
  "pbr": true,
  "planets": [
   {
    "key": "b",
    "name": "GJ 3323 b",
    "rE": 1.23,
    "au": 0.03282,
    "per": 5.3636,
    "kind": "warm rocky terrestrial planet",
    "massE": 2.02,
    "tempK": 290
   },
   {
    "key": "c",
    "name": "GJ 3323 c",
    "rE": 1.32,
    "au": 0.1264,
    "per": 40.54,
    "kind": "cold rocky",
    "massE": 2.31,
    "tempK": 148
   }
  ]
 },
 {
  "pack": "GJ_3470",
  "star": "GJ 3470",
  "ra": 7.9849,
  "dec": 15.3912,
  "ly": 95.96,
  "tempK": 3600,
  "spec": "M1.5",
  "rSun": 0.547,
  "col": 16761746,
  "pulsar": false,
  "kindStar": "red-dwarf star",
  "pbr": true,
  "planets": [
   {
    "key": "b",
    "name": "GJ 3470 b",
    "rE": 4.57,
    "au": 0.0355,
    "per": 3.3366,
    "kind": "warm evaporating volatile-rich mini-neptune",
    "massE": 13.9,
    "tempK": 594
   }
  ]
 },
 {
  "pack": "GJ_357",
  "star": "GJ 357",
  "ra": 9.6005,
  "dec": -21.6651,
  "ly": 30.795,
  "tempK": 3505,
  "spec": "M2.5 V",
  "rSun": 0.337,
  "col": 16761229,
  "pulsar": false,
  "kindStar": "red-dwarf star (main sequence)",
  "pbr": true,
  "planets": [
   {
    "key": "b",
    "name": "GJ 357 b",
    "rE": 1.2,
    "au": 0.036,
    "per": 3.9306,
    "kind": "rocky terrestrial or super-earth candidate",
    "massE": 1.83,
    "tempK": 518
   },
   {
    "key": "c",
    "name": "GJ 357 c",
    "rE": 1.66,
    "au": 0.061,
    "per": 9.1247,
    "kind": "rocky terrestrial or super-earth candidate",
    "massE": 3.4,
    "tempK": 401
   },
   {
    "key": "d",
    "name": "GJ 357 d",
    "rE": 2.34,
    "au": 0.204,
    "per": 55.661,
    "kind": "super-earth",
    "massE": 6.1,
    "tempK": 220
   }
  ]
 },
 {
  "pack": "GJ_367",
  "star": "GJ 367",
  "ra": 9.7414,
  "dec": -45.779,
  "ly": 30.7,
  "tempK": 3522,
  "spec": "M1.0 V",
  "rSun": 0.458,
  "col": 16761230,
  "pulsar": false,
  "kindStar": "red-dwarf star (main sequence)",
  "pbr": true,
  "planets": [
   {
    "key": "b",
    "name": "GJ 367 b",
    "rE": 0.699,
    "au": 0.00709,
    "per": 0.3219,
    "kind": "very hot rocky terrestrial planet",
    "massE": 0.633,
    "tempK": 1365
   },
   {
    "key": "c",
    "name": "GJ 367 c",
    "rE": 1.86,
    "au": 0.05,
    "per": 11.5301,
    "kind": "rocky super-earth",
    "massE": 4.13,
    "tempK": null
   },
   {
    "key": "d",
    "name": "GJ 367 d",
    "rE": 2.33,
    "au": 0.05,
    "per": 34.369,
    "kind": "rocky super-earth",
    "massE": 6.03,
    "tempK": null
   }
  ]
 },
 {
  "pack": "GJ_3929",
  "star": "GJ 3929",
  "ra": 15.9718,
  "dec": 35.4081,
  "ly": 51.564,
  "tempK": 3384,
  "spec": "M3.5 V",
  "rSun": 0.32,
  "col": 16760198,
  "pulsar": false,
  "kindStar": "red-dwarf star (main sequence)",
  "pbr": true,
  "planets": [
   {
    "key": "b",
    "name": "GJ 3929 b",
    "rE": 1.09,
    "au": 0.0252,
    "per": 2.6162,
    "kind": "hot rocky terrestrial planet",
    "massE": 1.75,
    "tempK": 568
   },
   {
    "key": "c",
    "name": "GJ 3929 c",
    "rE": 2.26,
    "au": 0.081,
    "per": 15.04,
    "kind": "temperate",
    "massE": 5.71,
    "tempK": 317
   }
  ]
 },
 {
  "pack": "GJ_433",
  "star": "GJ 433",
  "ra": 11.5908,
  "dec": -32.5436,
  "ly": 29.565,
  "tempK": 3461,
  "spec": "M2V",
  "rSun": 0.5,
  "col": 16760715,
  "pulsar": false,
  "kindStar": "red-dwarf star (main sequence)",
  "pbr": true,
  "planets": [
   {
    "key": "b",
    "name": "GJ 433 b",
    "rE": 2.33,
    "au": 0.062,
    "per": 7.3705,
    "kind": "hot",
    "massE": 6.043,
    "tempK": 474
   },
   {
    "key": "d",
    "name": "GJ 433 d",
    "rE": 2.14,
    "au": 0.178,
    "per": 36.059,
    "kind": "temperate low-density super-earth with possible volatile",
    "massE": 5.223,
    "tempK": 280
   },
   {
    "key": "c",
    "name": "GJ 433 c",
    "rE": 6.27,
    "au": 4.819,
    "per": 5094.105,
    "kind": "cool outer jovian gas giant",
    "massE": 32.422,
    "tempK": 54
   }
  ]
 },
 {
  "pack": "GJ_436",
  "star": "GJ 436",
  "ra": 11.7034,
  "dec": 26.7031,
  "ly": 31.811,
  "tempK": 3586,
  "spec": "M2.5 V",
  "rSun": 0.455,
  "col": 16761746,
  "pulsar": false,
  "kindStar": "red-dwarf star (main sequence)",
  "pbr": true,
  "planets": [
   {
    "key": "b",
    "name": "GJ 436 b",
    "rE": 4.17,
    "au": 0.0291,
    "per": 2.6439,
    "kind": "super-earth",
    "massE": 22.1,
    "tempK": 686
   }
  ]
 },
 {
  "pack": "GJ_486",
  "star": "GJ 486",
  "ra": 12.7988,
  "dec": 9.7494,
  "ly": 26.335,
  "tempK": 3317,
  "spec": "M3.5 V",
  "rSun": 0.324,
  "col": 16759682,
  "pulsar": false,
  "kindStar": "red-dwarf star (main sequence)",
  "pbr": true,
  "planets": [
   {
    "key": "b",
    "name": "GJ 486 b",
    "rE": 1.289,
    "au": 0.01714,
    "per": 1.4671,
    "kind": "hot rocky transiting super-earth",
    "massE": 2.77,
    "tempK": 696
   }
  ]
 },
 {
  "pack": "GJ_514",
  "star": "GJ 514",
  "ra": 13.5003,
  "dec": 10.3725,
  "ly": 24.846,
  "tempK": 3728,
  "spec": "M0.5-1.0 V",
  "rSun": 0.5,
  "col": 16762777,
  "pulsar": false,
  "kindStar": "red-dwarf star (main sequence)",
  "pbr": true,
  "planets": [
   {
    "key": "b",
    "name": "GJ 514 b",
    "rE": 2.13,
    "au": 0.422,
    "per": 140.43,
    "kind": "cold volatile",
    "massE": 5.2,
    "tempK": 202
   }
  ]
 },
 {
  "pack": "GJ_581",
  "star": "GJ 581",
  "ra": 15.3238,
  "dec": -7.7227,
  "ly": 20.542,
  "tempK": 3500,
  "spec": "M3.0 V",
  "rSun": 0.302,
  "col": 16761229,
  "pulsar": false,
  "kindStar": "red-dwarf star (main sequence)",
  "pbr": true,
  "planets": [
   {
    "key": "e",
    "name": "GJ 581 e",
    "rE": 1.38,
    "au": 0.02799,
    "per": 3.1481,
    "kind": "very hot rocky terrestrial planet",
    "massE": 2.48,
    "tempK": 554
   },
   {
    "key": "b",
    "name": "GJ 581 b",
    "rE": 4.79,
    "au": 0.0399,
    "per": 5.3686,
    "kind": "hot volatile-rich sub-neptune",
    "massE": 20.5,
    "tempK": 464
   },
   {
    "key": "c",
    "name": "GJ 581 c",
    "rE": 2.5,
    "au": 0.0718,
    "per": 12.9211,
    "kind": "warm volatile-rich sub-neptune",
    "massE": 6.81,
    "tempK": 346
   }
  ]
 },
 {
  "pack": "GJ_625",
  "star": "GJ 625",
  "ra": 16.4237,
  "dec": 54.3034,
  "ly": 21.11,
  "tempK": 3499,
  "spec": "M2",
  "rSun": 0.31,
  "col": 16761229,
  "pulsar": false,
  "kindStar": "red-dwarf star",
  "pbr": true,
  "planets": [
   {
    "key": "b",
    "name": "GJ 625 b",
    "rE": 1.49,
    "au": 0.07836,
    "per": 14.628,
    "kind": "warm rocky terrestrial planet",
    "massE": 2.82,
    "tempK": 336
   }
  ]
 },
 {
  "pack": "GJ_667_C",
  "star": "GJ 667 C",
  "ra": 17.3167,
  "dec": -34.9978,
  "ly": 23.627,
  "tempK": 3350,
  "spec": "M1.5 V",
  "rSun": 1,
  "col": 16759940,
  "pulsar": false,
  "kindStar": "red-dwarf star (main sequence)",
  "pbr": true,
  "planets": [
   {
    "key": "b",
    "name": "GJ 667 C b",
    "rE": 2.25,
    "au": 0.05043,
    "per": 7.203,
    "kind": "super-earth",
    "massE": 5.68,
    "tempK": null
   },
   {
    "key": "c",
    "name": "GJ 667 C c",
    "rE": 1.77,
    "au": 0.125,
    "per": 28.14,
    "kind": "rocky terrestrial or super-earth candidate",
    "massE": 3.8,
    "tempK": null
   }
  ]
 },
 {
  "pack": "GJ_674",
  "star": "GJ 674",
  "ra": 17.478,
  "dec": -46.899,
  "ly": 14.837,
  "tempK": 3600,
  "spec": "M2.5",
  "rSun": 0.365,
  "col": 16761746,
  "pulsar": false,
  "kindStar": "red-dwarf star",
  "pbr": true,
  "planets": [
   {
    "key": "b",
    "name": "GJ 674 b",
    "rE": 3.33,
    "au": 0.039,
    "per": 4.6938,
    "kind": "hot volatile-rich sub-neptune",
    "massE": 11.09,
    "tempK": 531
   }
  ]
 },
 {
  "pack": "GJ_682",
  "star": "GJ 682",
  "ra": 17.6174,
  "dec": -44.3233,
  "ly": 16.33,
  "tempK": 3028,
  "spec": "M3.5 V",
  "rSun": 0.298,
  "col": 16757360,
  "pulsar": false,
  "kindStar": "red-dwarf star (main sequence)",
  "pbr": true,
  "planets": [
   {
    "key": "b",
    "name": "GJ 682 b",
    "rE": 1.93,
    "au": 0.08,
    "per": 17.478,
    "kind": "temperate low-density super-earth with possible volatile",
    "massE": 4.4,
    "tempK": 282
   },
   {
    "key": "c",
    "name": "GJ 682 c",
    "rE": 2.89,
    "au": 0.176,
    "per": 57.32,
    "kind": "cold volatile-rich mini-neptune",
    "massE": 8.7,
    "tempK": 190
   }
  ]
 },
 {
  "pack": "GJ_832",
  "star": "GJ 832",
  "ra": 21.5594,
  "dec": -49.0125,
  "ly": 16.192,
  "tempK": 3472,
  "spec": "M2/3 V",
  "rSun": 0.442,
  "col": 16760971,
  "pulsar": false,
  "kindStar": "red-dwarf star (main sequence)",
  "pbr": true,
  "planets": [
   {
    "key": "b",
    "name": "GJ 832 b",
    "rE": 13.8,
    "au": 3.7,
    "per": 3853,
    "kind": "cool outer jovian gas giant",
    "massE": 314.65,
    "tempK": 58
   }
  ]
 },
 {
  "pack": "GJ_849",
  "star": "GJ 849",
  "ra": 22.1615,
  "dec": -4.6408,
  "ly": 28.704,
  "tempK": 3467,
  "spec": "M3.5",
  "rSun": 0.45,
  "col": 16760971,
  "pulsar": false,
  "kindStar": "red-dwarf star",
  "pbr": true,
  "planets": [
   {
    "key": "b",
    "name": "GJ 849 b",
    "rE": 13.9,
    "au": 2.32,
    "per": 1925.31,
    "kind": "cool outer jovian gas giant",
    "massE": 283.821,
    "tempK": 74
   },
   {
    "key": "c",
    "name": "GJ 849 c",
    "rE": 13.8,
    "au": 4.95,
    "per": 5990,
    "kind": "cool outer jovian gas giant",
    "massE": 314.65,
    "tempK": 50
   }
  ]
 },
 {
  "pack": "GJ_876",
  "star": "GJ 876",
  "ra": 22.8883,
  "dec": -14.2666,
  "ly": 15.248,
  "tempK": 3294,
  "spec": "M2.5V",
  "rSun": 0.3,
  "col": 16759425,
  "pulsar": false,
  "kindStar": "red-dwarf star (main sequence)",
  "pbr": true,
  "planets": [
   {
    "key": "d",
    "name": "GJ 876 d",
    "rE": 2.51,
    "au": 0.02081,
    "per": 1.9378,
    "kind": "super-earth",
    "massE": 6.83,
    "tempK": 603
   },
   {
    "key": "c",
    "name": "GJ 876 c",
    "rE": 14,
    "au": 0.12959,
    "per": 30.0881,
    "kind": "gas giant",
    "massE": 226.985,
    "tempK": 242
   },
   {
    "key": "b",
    "name": "GJ 876 b",
    "rE": 13.3,
    "au": 0.20832,
    "per": 61.1166,
    "kind": "gas giant",
    "massE": 723.223,
    "tempK": 191
   },
   {
    "key": "e",
    "name": "GJ 876 e",
    "rE": 3.92,
    "au": 0.3343,
    "per": 124.26,
    "kind": "super-earth",
    "massE": 14.6,
    "tempK": 150
   }
  ]
 },
 {
  "pack": "GJ_887",
  "star": "GJ 887",
  "ra": 23.1002,
  "dec": -35.8473,
  "ly": 10.72,
  "tempK": 3688,
  "spec": "M1 V",
  "rSun": 0.468,
  "col": 16762519,
  "pulsar": false,
  "kindStar": "red-dwarf star (main sequence)",
  "pbr": true,
  "planets": [
   {
    "key": "e",
    "name": "GJ 887 e",
    "rE": 1.12,
    "au": 0.0417,
    "per": 4.4249,
    "kind": "rocky terrestrial or super-earth candidate",
    "massE": 1.46,
    "tempK": 544
   },
   {
    "key": "b",
    "name": "GJ 887 b",
    "rE": 1.8,
    "au": 0.0683,
    "per": 9.2619,
    "kind": "super-earth",
    "massE": 3.9,
    "tempK": 426
   },
   {
    "key": "c",
    "name": "GJ 887 c",
    "rE": 2.43,
    "au": 0.121,
    "per": 21.784,
    "kind": "super-earth",
    "massE": 6.5,
    "tempK": 320
   },
   {
    "key": "d",
    "name": "GJ 887 d",
    "rE": 2.34,
    "au": 0.212,
    "per": 50.77,
    "kind": "super-earth",
    "massE": 6.1,
    "tempK": 241
   }
  ]
 },
 {
  "pack": "HD_110067",
  "star": "HD 110067",
  "ra": 12.6559,
  "dec": 20.0273,
  "ly": 104.887,
  "tempK": 5266,
  "spec": "K0.0 V",
  "rSun": 0.788,
  "col": 16771543,
  "pulsar": false,
  "kindStar": "orange K-type dwarf (main sequence)",
  "pbr": true,
  "planets": [
   {
    "key": "b",
    "name": "HD 110067 b",
    "rE": 2.2,
    "au": 0.0793,
    "per": 9.1137,
    "kind": "warm sub-neptune",
    "massE": 5.69,
    "tempK": 800
   },
   {
    "key": "c",
    "name": "HD 110067 c",
    "rE": 2.388,
    "au": 0.1039,
    "per": 13.6737,
    "kind": "warm sub-neptune",
    "massE": 6.3,
    "tempK": 699
   },
   {
    "key": "d",
    "name": "HD 110067 d",
    "rE": 2.852,
    "au": 0.1362,
    "per": 20.5196,
    "kind": "warm sub-neptune",
    "massE": 8.52,
    "tempK": 602
   },
   {
    "key": "e",
    "name": "HD 110067 e",
    "rE": 1.94,
    "au": 0.1785,
    "per": 30.7931,
    "kind": "warm sub-neptune",
    "massE": 3.9,
    "tempK": 533
   },
   {
    "key": "f",
    "name": "HD 110067 f",
    "rE": 2.601,
    "au": 0.2163,
    "per": 41.0585,
    "kind": "warm sub-neptune",
    "massE": 5.04,
    "tempK": 489
   },
   {
    "key": "g",
    "name": "HD 110067 g",
    "rE": 2.607,
    "au": 0.2621,
    "per": 54.7699,
    "kind": "warm sub-neptune",
    "massE": 8.4,
    "tempK": 440
   }
  ]
 },
 {
  "pack": "HD_15337",
  "star": "HD 15337",
  "ra": 2.4579,
  "dec": -27.6361,
  "ly": 146.169,
  "tempK": 5131,
  "spec": "K1 V",
  "rSun": 0.855,
  "col": 16771026,
  "pulsar": false,
  "kindStar": "orange K-type dwarf (main sequence)",
  "pbr": true,
  "planets": [
   {
    "key": "b",
    "name": "HD 15337 b",
    "rE": 1.77,
    "au": 0.05245,
    "per": 4.756,
    "kind": "ultra-hot dense rocky super-earth",
    "massE": 6.519,
    "tempK": 1001
   },
   {
    "key": "c",
    "name": "HD 15337 c",
    "rE": 2.526,
    "au": 0.1235,
    "per": 17.1805,
    "kind": "hot volatile-rich sub-neptune",
    "massE": 6.792,
    "tempK": 656
   }
  ]
 },
 {
  "pack": "HD_189733",
  "star": "HD 189733",
  "ra": 20.0121,
  "dec": 22.7098,
  "ly": 64.461,
  "tempK": 5052,
  "spec": "K2 V",
  "rSun": 0.75,
  "col": 16770512,
  "pulsar": false,
  "kindStar": "orange K-type dwarf (main sequence)",
  "pbr": true,
  "planets": [
   {
    "key": "b",
    "name": "HD 189733 b",
    "rE": 12.666,
    "au": 0.03126,
    "per": 2.2186,
    "kind": "gas giant",
    "massE": 359.148,
    "tempK": 1209
   }
  ]
 },
 {
  "pack": "HD_209458",
  "star": "HD 209458",
  "ra": 22.053,
  "dec": 18.8842,
  "ly": 157.539,
  "tempK": 6091,
  "spec": "G0 V",
  "rSun": 1.19,
  "col": 16775407,
  "pulsar": false,
  "kindStar": "Sun-like G-type star (main sequence)",
  "pbr": true,
  "planets": [
   {
    "key": "b",
    "name": "HD 209458 b",
    "rE": 15.581,
    "au": 0.04707,
    "per": 3.5247,
    "kind": "gas giant",
    "massE": 232.016,
    "tempK": 1459
   }
  ]
 },
 {
  "pack": "HD_219134",
  "star": "HD 219134",
  "ra": 23.2225,
  "dec": 57.1696,
  "ly": 21.302,
  "tempK": 4699,
  "spec": "K3 V",
  "rSun": 0.778,
  "col": 16768707,
  "pulsar": false,
  "kindStar": "orange K-type dwarf (main sequence)",
  "pbr": true,
  "planets": [
   {
    "key": "b",
    "name": "HD 219134 b",
    "rE": 1.602,
    "au": 0.03876,
    "per": 3.0929,
    "kind": "hot rocky planet",
    "massE": 4.74,
    "tempK": 1015
   },
   {
    "key": "c",
    "name": "HD 219134 c",
    "rE": 1.511,
    "au": 0.0653,
    "per": 6.7646,
    "kind": "hot rocky planet",
    "massE": 4.36,
    "tempK": 782
   },
   {
    "key": "d",
    "name": "HD 219134 d",
    "rE": 1.61,
    "au": 0.237,
    "per": 46.859,
    "kind": "rocky terrestrial or super-earth candidate",
    "massE": 16.17,
    "tempK": 411
   },
   {
    "key": "h",
    "name": "HD 219134 h",
    "rE": 12.7,
    "au": 3.11,
    "per": 2247,
    "kind": "gas giant",
    "massE": 108.062,
    "tempK": 118
   }
  ]
 },
 {
  "pack": "HD_260655",
  "star": "HD 260655",
  "ra": 6.6194,
  "dec": 17.5663,
  "ly": 32.634,
  "tempK": 3803,
  "spec": "M0 V",
  "rSun": 0.439,
  "col": 16763293,
  "pulsar": false,
  "kindStar": "red-dwarf star (main sequence)",
  "pbr": true,
  "planets": [
   {
    "key": "b",
    "name": "HD 260655 b",
    "rE": 1.24,
    "au": 0.02933,
    "per": 2.7695,
    "kind": "hot rocky terrestrial planet",
    "massE": 2.14,
    "tempK": 709
   },
   {
    "key": "c",
    "name": "HD 260655 c",
    "rE": 1.533,
    "au": 0.04749,
    "per": 5.7059,
    "kind": "hot",
    "massE": 3.09,
    "tempK": 557
   }
  ]
 },
 {
  "pack": "HD_3167",
  "star": "HD 3167",
  "ra": 0.5827,
  "dec": 4.3807,
  "ly": 154.239,
  "tempK": 5261,
  "spec": "K0 V",
  "rSun": 0.88,
  "col": 16771543,
  "pulsar": false,
  "kindStar": "orange K-type dwarf (main sequence)",
  "pbr": true,
  "planets": [
   {
    "key": "b",
    "name": "HD 3167 b",
    "rE": 1.67,
    "au": 0.01796,
    "per": 0.9596,
    "kind": "ultra-hot dense rocky super-earth",
    "massE": 4.97,
    "tempK": 1774
   },
   {
    "key": "d",
    "name": "HD 3167 d",
    "rE": 1.92,
    "au": 0.0763,
    "per": 8.4112,
    "kind": "hot low-density super-earth with possible volatile envelope",
    "massE": 4.33,
    "tempK": 860
   },
   {
    "key": "c",
    "name": "HD 3167 c",
    "rE": 3,
    "au": 0.1776,
    "per": 29.8454,
    "kind": "warm",
    "massE": 11.13,
    "tempK": 564
   },
   {
    "key": "e",
    "name": "HD 3167 e",
    "rE": 2.83,
    "au": 0.3885,
    "per": 96.63,
    "kind": "warm volatile-rich sub-neptune",
    "massE": 8.41,
    "tempK": 375
   }
  ]
 },
 {
  "pack": "HD_40307",
  "star": "HD 40307",
  "ra": 5.9011,
  "dec": -60.0237,
  "ly": 42.193,
  "tempK": 4956,
  "spec": "K2.5 V",
  "rSun": 0.717,
  "col": 16769996,
  "pulsar": false,
  "kindStar": "orange K-type dwarf (main sequence)",
  "pbr": true,
  "planets": [
   {
    "key": "b",
    "name": "HD 40307 b",
    "rE": 11.2,
    "au": 0.0468,
    "per": 4.3123,
    "kind": "gas giant",
    "massE": 1188.996,
    "tempK": 910
   },
   {
    "key": "c",
    "name": "HD 40307 c",
    "rE": 11.2,
    "au": 0.0799,
    "per": 9.6184,
    "kind": "gas giant",
    "massE": 1868.513,
    "tempK": 696
   },
   {
    "key": "d",
    "name": "HD 40307 d",
    "rE": 11.2,
    "au": 0.1321,
    "per": 20.432,
    "kind": "gas giant",
    "massE": 1775.389,
    "tempK": 541
   },
   {
    "key": "f",
    "name": "HD 40307 f",
    "rE": 2.13,
    "au": 0.247,
    "per": 51.76,
    "kind": "super-earth",
    "massE": 5.2,
    "tempK": 398
   }
  ]
 },
 {
  "pack": "HD_73583",
  "star": "HD 73583",
  "ra": 8.6459,
  "dec": -13.2565,
  "ly": 102.956,
  "tempK": 4511,
  "spec": "K4 V",
  "rSun": 0.65,
  "col": 16767676,
  "pulsar": false,
  "kindStar": "orange K-type dwarf (main sequence)",
  "pbr": true,
  "planets": [
   {
    "key": "b",
    "name": "HD 73583 b",
    "rE": 2.79,
    "au": 0.0604,
    "per": 6.398,
    "kind": "hot volatile-rich sub-neptune",
    "massE": 10.2,
    "tempK": 714
   },
   {
    "key": "c",
    "name": "HD 73583 c",
    "rE": 2.39,
    "au": 0.1242,
    "per": 18.8797,
    "kind": "warm low-density super-earth with possible volatile envelope",
    "massE": 9.7,
    "tempK": 498
   }
  ]
 },
 {
  "pack": "HD_97658",
  "star": "HD 97658",
  "ra": 11.2425,
  "dec": 25.7106,
  "ly": 70.325,
  "tempK": 5212,
  "spec": "K1 V",
  "rSun": 0.728,
  "col": 16771285,
  "pulsar": false,
  "kindStar": "orange K-type dwarf (main sequence)",
  "pbr": true,
  "planets": [
   {
    "key": "b",
    "name": "HD 97658 b",
    "rE": 2.12,
    "au": 0.0805,
    "per": 9.4897,
    "kind": "hot",
    "massE": 8.3,
    "tempK": 751
   }
  ]
 },
 {
  "pack": "HR_8799",
  "star": "HR 8799",
  "ra": 23.1247,
  "dec": 21.134,
  "ly": 134.52,
  "tempK": 7400,
  "spec": "A5 V",
  "rSun": 1.493,
  "col": 15265023,
  "pulsar": false,
  "kindStar": "white A-type star (main sequence)",
  "pbr": true,
  "planets": [
   {
    "key": "e",
    "name": "HR 8799 e",
    "rE": 13.115,
    "au": 16.4,
    "per": 20815.6,
    "kind": "gas giant",
    "massE": 3178.3,
    "tempK": 1150
   },
   {
    "key": "d",
    "name": "HR 8799 d",
    "rE": 13,
    "au": 24,
    "per": 37000,
    "kind": "gas giant",
    "massE": 3000,
    "tempK": 1300
   },
   {
    "key": "c",
    "name": "HR 8799 c",
    "rE": 13,
    "au": 38,
    "per": 69000,
    "kind": "gas giant",
    "massE": 3000,
    "tempK": 1200
   },
   {
    "key": "b",
    "name": "HR 8799 b",
    "rE": 13,
    "au": 68,
    "per": 170000,
    "kind": "gas giant",
    "massE": 2000,
    "tempK": 1200
   }
  ]
 },
 {
  "pack": "K2_138",
  "star": "K2-138",
  "ra": 23.2633,
  "dec": -10.8497,
  "ly": 660.744,
  "tempK": 5356,
  "spec": "G8 V",
  "rSun": 0.863,
  "col": 16772058,
  "pulsar": false,
  "kindStar": "Sun-like G-type star (main sequence)",
  "pbr": true,
  "planets": [
   {
    "key": "b",
    "name": "K2-138 b",
    "rE": 1.51,
    "au": 0.03385,
    "per": 2.3531,
    "kind": "hot rocky planet",
    "massE": 3.1,
    "tempK": 1157
   },
   {
    "key": "c",
    "name": "K2-138 c",
    "rE": 2.299,
    "au": 0.04461,
    "per": 3.56,
    "kind": "super-earth",
    "massE": 6.31,
    "tempK": 1012
   },
   {
    "key": "d",
    "name": "K2-138 d",
    "rE": 2.39,
    "au": 0.05893,
    "per": 5.4048,
    "kind": "super-earth",
    "massE": 7.92,
    "tempK": 888
   },
   {
    "key": "e",
    "name": "K2-138 e",
    "rE": 3.39,
    "au": 0.0782,
    "per": 8.2615,
    "kind": "super-earth",
    "massE": 12.97,
    "tempK": 757
   },
   {
    "key": "f",
    "name": "K2-138 f",
    "rE": 2.904,
    "au": 0.10447,
    "per": 12.7576,
    "kind": "super-earth",
    "massE": 1.63,
    "tempK": 653
   },
   {
    "key": "g",
    "name": "K2-138 g",
    "rE": 3.013,
    "au": 0.23109,
    "per": 41.968,
    "kind": "super-earth",
    "massE": 4.32,
    "tempK": 445
   }
  ]
 },
 {
  "pack": "K2_18",
  "star": "K2-18",
  "ra": 11.504,
  "dec": 7.5878,
  "ly": 124.026,
  "tempK": 3457,
  "spec": "M2.5 V",
  "rSun": 0.411,
  "col": 16760714,
  "pulsar": false,
  "kindStar": "red-dwarf star (main sequence)",
  "pbr": true,
  "planets": [
   {
    "key": "b",
    "name": "K2-18 b",
    "rE": 2.37,
    "au": 0.1429,
    "per": 32.9396,
    "kind": "super-earth",
    "massE": 8.92,
    "tempK": 284
   }
  ]
 },
 {
  "pack": "K2_72",
  "star": "K2-72",
  "ra": 22.3082,
  "dec": -9.612,
  "ly": 216.673,
  "tempK": 3360,
  "spec": "—",
  "rSun": 0.331,
  "col": 16759941,
  "pulsar": false,
  "kindStar": "red-dwarf star",
  "pbr": true,
  "planets": [
   {
    "key": "b",
    "name": "K2-72 b",
    "rE": 1.08,
    "au": 0.04,
    "per": 5.5772,
    "kind": "rocky terrestrial or super-earth candidate",
    "massE": 1.28,
    "tempK": 466
   },
   {
    "key": "d",
    "name": "K2-72 d",
    "rE": 1.01,
    "au": 0.05,
    "per": 7.7602,
    "kind": "rocky terrestrial or super-earth candidate",
    "massE": 1.01,
    "tempK": 417
   },
   {
    "key": "c",
    "name": "K2-72 c",
    "rE": 1.16,
    "au": 0.078,
    "per": 15.189,
    "kind": "rocky terrestrial or super-earth candidate",
    "massE": 1.65,
    "tempK": 334
   },
   {
    "key": "e",
    "name": "K2-72 e",
    "rE": 1.29,
    "au": 0.106,
    "per": 24.1589,
    "kind": "earth-size",
    "massE": 2.21,
    "tempK": 286
   }
  ]
 },
 {
  "pack": "Kepler_10",
  "star": "Kepler-10",
  "ra": 19.0453,
  "dec": 50.2415,
  "ly": 605.04,
  "tempK": 5708,
  "spec": "—",
  "rSun": 1.065,
  "col": 16773605,
  "pulsar": false,
  "kindStar": "Sun-like G-type star",
  "pbr": true,
  "planets": [
   {
    "key": "b",
    "name": "Kepler-10 b",
    "rE": 1.47,
    "au": 0.01685,
    "per": 0.8375,
    "kind": "hot rocky planet",
    "massE": 3.24,
    "tempK": 2188
   },
   {
    "key": "c",
    "name": "Kepler-10 c",
    "rE": 2.355,
    "au": 0.241,
    "per": 45.2943,
    "kind": "super-earth",
    "massE": 11.29,
    "tempK": 579
   },
   {
    "key": "d",
    "name": "Kepler-10 d",
    "rE": 3.49,
    "au": 0.5379,
    "per": 151.06,
    "kind": "super-earth",
    "massE": 12,
    "tempK": 387
   }
  ]
 },
 {
  "pack": "Kepler_11",
  "star": "Kepler-11",
  "ra": 19.8077,
  "dec": 41.9091,
  "ly": 2108.099,
  "tempK": 5663,
  "spec": "—",
  "rSun": 1.065,
  "col": 16773347,
  "pulsar": false,
  "kindStar": "Sun-like G-type star",
  "pbr": true,
  "planets": [
   {
    "key": "b",
    "name": "Kepler-11 b",
    "rE": 1.8,
    "au": 0.091,
    "per": 10.3039,
    "kind": "super-earth",
    "massE": 1.9,
    "tempK": 849
   },
   {
    "key": "c",
    "name": "Kepler-11 c",
    "rE": 2.87,
    "au": 0.107,
    "per": 13.0241,
    "kind": "super-earth",
    "massE": 2.9,
    "tempK": 786
   },
   {
    "key": "d",
    "name": "Kepler-11 d",
    "rE": 3.12,
    "au": 0.155,
    "per": 22.6845,
    "kind": "super-earth",
    "massE": 7.3,
    "tempK": 653
   },
   {
    "key": "e",
    "name": "Kepler-11 e",
    "rE": 4.19,
    "au": 0.195,
    "per": 31.9996,
    "kind": "super-earth",
    "massE": 8,
    "tempK": 582
   },
   {
    "key": "f",
    "name": "Kepler-11 f",
    "rE": 2.49,
    "au": 0.25,
    "per": 46.6888,
    "kind": "super-earth",
    "massE": 2,
    "tempK": 513
   },
   {
    "key": "g",
    "name": "Kepler-11 g",
    "rE": 3.33,
    "au": 0.466,
    "per": 118.3807,
    "kind": "super-earth",
    "massE": 25,
    "tempK": 376
   }
  ]
 },
 {
  "pack": "Kepler_138",
  "star": "Kepler-138",
  "ra": 19.3588,
  "dec": 43.2931,
  "ly": 218.076,
  "tempK": 3841,
  "spec": "M1 V",
  "rSun": 0.535,
  "col": 16763551,
  "pulsar": false,
  "kindStar": "red-dwarf star (main sequence)",
  "pbr": true,
  "planets": [
   {
    "key": "b",
    "name": "Kepler-138 b",
    "rE": 0.64,
    "au": 0.0753,
    "per": 10.3134,
    "kind": "rocky terrestrial or super-earth candidate",
    "massE": 0.07,
    "tempK": 452
   },
   {
    "key": "c",
    "name": "Kepler-138 c",
    "rE": 1.51,
    "au": 0.0913,
    "per": 13.7815,
    "kind": "likely water-rich super-earth",
    "massE": 2.3,
    "tempK": 410
   },
   {
    "key": "d",
    "name": "Kepler-138 d",
    "rE": 1.51,
    "au": 0.1288,
    "per": 23.0923,
    "kind": "likely water-rich super-earth",
    "massE": 2.1,
    "tempK": 345
   },
   {
    "key": "e",
    "name": "Kepler-138 e",
    "rE": 0.797,
    "au": 0.1803,
    "per": 38.23,
    "kind": "earth-size",
    "massE": 0.43,
    "tempK": 292
   }
  ]
 },
 {
  "pack": "Kepler_1649",
  "star": "Kepler-1649",
  "ra": 19.5002,
  "dec": 41.83,
  "ly": 300.688,
  "tempK": 3240,
  "spec": "—",
  "rSun": 0.232,
  "col": 16759166,
  "pulsar": false,
  "kindStar": "red-dwarf star",
  "pbr": true,
  "planets": [
   {
    "key": "b",
    "name": "Kepler-1649 b",
    "rE": 1.017,
    "au": 0.0514,
    "per": 8.6891,
    "kind": "inner warm rocky",
    "massE": 1.03,
    "tempK": 307
   },
   {
    "key": "c",
    "name": "Kepler-1649 c",
    "rE": 1.06,
    "au": 0.0649,
    "per": 19.5353,
    "kind": "earth-size habitable-zone rocky candidate",
    "massE": 1.2,
    "tempK": 234
   }
  ]
 },
 {
  "pack": "Kepler_16",
  "star": "Kepler-16",
  "ra": 19.2717,
  "dec": 51.7572,
  "ly": 244.895,
  "tempK": 4450,
  "spec": "—",
  "rSun": 0.649,
  "col": 16767161,
  "pulsar": false,
  "kindStar": "orange K-type dwarf",
  "pbr": true,
  "planets": [
   {
    "key": "b",
    "name": "Kepler-16 b",
    "rE": 8.449,
    "au": 0.7048,
    "per": 228.776,
    "kind": "gas giant",
    "massE": 105.833,
    "tempK": 206
   }
  ]
 },
 {
  "pack": "Kepler_186",
  "star": "Kepler-186",
  "ra": 19.9102,
  "dec": 43.955,
  "ly": 579.234,
  "tempK": 3788,
  "spec": "M1",
  "rSun": 0.472,
  "col": 16763036,
  "pulsar": false,
  "kindStar": "red-dwarf star",
  "pbr": true,
  "planets": [
   {
    "key": "b",
    "name": "Kepler-186 b",
    "rE": 1.07,
    "au": 0.0343,
    "per": 3.8868,
    "kind": "rocky terrestrial or super-earth candidate",
    "massE": 1.24,
    "tempK": 571
   },
   {
    "key": "c",
    "name": "Kepler-186 c",
    "rE": 1.25,
    "au": 0.0451,
    "per": 7.2673,
    "kind": "rocky terrestrial or super-earth candidate",
    "massE": 2.1,
    "tempK": 464
   },
   {
    "key": "d",
    "name": "Kepler-186 d",
    "rE": 1.4,
    "au": 0.0781,
    "per": 13.343,
    "kind": "rocky terrestrial or super-earth candidate",
    "massE": 2.54,
    "tempK": 379
   },
   {
    "key": "e",
    "name": "Kepler-186 e",
    "rE": 1.27,
    "au": 0.11,
    "per": 22.4077,
    "kind": "rocky terrestrial or super-earth candidate",
    "massE": 2.15,
    "tempK": 319
   },
   {
    "key": "f",
    "name": "Kepler-186 f",
    "rE": 1.17,
    "au": 0.356,
    "per": 129.9441,
    "kind": "earth-size habitable-zone rocky candidate",
    "massE": 1.7,
    "tempK": 188
   }
  ]
 },
 {
  "pack": "Kepler_20",
  "star": "Kepler-20",
  "ra": 19.1799,
  "dec": 42.3386,
  "ly": 921.597,
  "tempK": 5495,
  "spec": "—",
  "rSun": 0.916,
  "col": 16772574,
  "pulsar": false,
  "kindStar": "Sun-like G-type star",
  "pbr": true,
  "planets": [
   {
    "key": "b",
    "name": "Kepler-20 b",
    "rE": 1.773,
    "au": 0.04565,
    "per": 3.6961,
    "kind": "hot rocky planet",
    "massE": 9.7,
    "tempK": 1187
   },
   {
    "key": "e",
    "name": "Kepler-20 e",
    "rE": 0.821,
    "au": 0.0637,
    "per": 6.0985,
    "kind": "hot rocky planet",
    "massE": 0.76,
    "tempK": 1004
   },
   {
    "key": "c",
    "name": "Kepler-20 c",
    "rE": 2.894,
    "au": 0.0936,
    "per": 10.8541,
    "kind": "super-earth",
    "massE": 11.1,
    "tempK": 828
   },
   {
    "key": "f",
    "name": "Kepler-20 f",
    "rE": 0.952,
    "au": 0.1387,
    "per": 19.5783,
    "kind": "hot rocky planet",
    "massE": 1.4,
    "tempK": 681
   },
   {
    "key": "g",
    "name": "Kepler-20 g",
    "rE": 4.71,
    "au": 0.2055,
    "per": 34.94,
    "kind": "super-earth",
    "massE": 19.96,
    "tempK": 524
   },
   {
    "key": "d",
    "name": "Kepler-20 d",
    "rE": 2.606,
    "au": 0.3474,
    "per": 77.6115,
    "kind": "super-earth",
    "massE": 13.4,
    "tempK": 430
   }
  ]
 },
 {
  "pack": "Kepler_22",
  "star": "Kepler-22",
  "ra": 19.2811,
  "dec": 47.8841,
  "ly": 634.837,
  "tempK": 5596,
  "spec": "G5 V",
  "rSun": 0.869,
  "col": 16773089,
  "pulsar": false,
  "kindStar": "Sun-like G-type star (main sequence)",
  "pbr": true,
  "planets": [
   {
    "key": "b",
    "name": "Kepler-22 b",
    "rE": 2.1,
    "au": 0.812,
    "per": 289.8639,
    "kind": "super-earth",
    "massE": 9.1,
    "tempK": 279
   }
  ]
 },
 {
  "pack": "Kepler_296",
  "star": "Kepler-296",
  "ra": 19.1027,
  "dec": 49.4373,
  "ly": 544.681,
  "tempK": 3740,
  "spec": "M2 V",
  "rSun": 0.48,
  "col": 16762778,
  "pulsar": false,
  "kindStar": "red-dwarf star (main sequence)",
  "pbr": true,
  "planets": [
   {
    "key": "c",
    "name": "Kepler-296 c",
    "rE": 2,
    "au": 0.0521,
    "per": 5.8416,
    "kind": "super-earth",
    "massE": 4.66,
    "tempK": 606
   },
   {
    "key": "b",
    "name": "Kepler-296 b",
    "rE": 1.61,
    "au": 0.079,
    "per": 10.8644,
    "kind": "rocky terrestrial or super-earth candidate",
    "massE": 3.22,
    "tempK": 495
   },
   {
    "key": "d",
    "name": "Kepler-296 d",
    "rE": 2.09,
    "au": 0.118,
    "per": 19.8503,
    "kind": "super-earth",
    "massE": 5.02,
    "tempK": 403
   },
   {
    "key": "e",
    "name": "Kepler-296 e",
    "rE": 1.53,
    "au": 0.169,
    "per": 34.1421,
    "kind": "rocky terrestrial or super-earth candidate",
    "massE": 2.96,
    "tempK": 337
   },
   {
    "key": "f",
    "name": "Kepler-296 f",
    "rE": 1.8,
    "au": 0.255,
    "per": 63.3363,
    "kind": "super-earth",
    "massE": 3.89,
    "tempK": 274
   }
  ]
 },
 {
  "pack": "Kepler_37",
  "star": "Kepler-37",
  "ra": 18.9373,
  "dec": 44.5184,
  "ly": 208.481,
  "tempK": 5357,
  "spec": "—",
  "rSun": 0.789,
  "col": 16772058,
  "pulsar": false,
  "kindStar": "Sun-like G-type star",
  "pbr": true,
  "planets": [
   {
    "key": "b",
    "name": "Kepler-37 b",
    "rE": 0.31,
    "au": 0.1019,
    "per": 13.367,
    "kind": "hot rocky planet",
    "massE": 0.79,
    "tempK": 718
   },
   {
    "key": "c",
    "name": "Kepler-37 c",
    "rE": 0.755,
    "au": 0.139,
    "per": 21.3018,
    "kind": "rocky terrestrial or super-earth candidate",
    "massE": 1.3,
    "tempK": 615
   },
   {
    "key": "d",
    "name": "Kepler-37 d",
    "rE": 2.03,
    "au": 0.2109,
    "per": 39.7923,
    "kind": "super-earth",
    "massE": 2,
    "tempK": 499
   },
   {
    "key": "e",
    "name": "Kepler-37 e",
    "rE": 0.37,
    "au": 0.25,
    "per": 51.196,
    "kind": "uncertain compact rocky candidate (visual assumption follows pack geometry)",
    "massE": 8.1,
    "tempK": 401
   }
  ]
 },
 {
  "pack": "Kepler_442",
  "star": "Kepler-442",
  "ra": 19.0244,
  "dec": 39.2801,
  "ly": 1193.618,
  "tempK": 4402,
  "spec": "—",
  "rSun": 0.598,
  "col": 16766904,
  "pulsar": false,
  "kindStar": "orange K-type dwarf",
  "pbr": true,
  "planets": [
   {
    "key": "b",
    "name": "Kepler-442 b",
    "rE": 1.34,
    "au": 0.409,
    "per": 112.3053,
    "kind": "earth-size",
    "massE": 2.36,
    "tempK": 241
   }
  ]
 },
 {
  "pack": "Kepler_444",
  "star": "Kepler-444",
  "ra": 19.3169,
  "dec": 41.6319,
  "ly": 118.85,
  "tempK": 5046,
  "spec": "K",
  "rSun": 0.752,
  "col": 16770512,
  "pulsar": false,
  "kindStar": "orange K-type dwarf",
  "pbr": true,
  "planets": [
   {
    "key": "b",
    "name": "Kepler-444 b",
    "rE": 0.403,
    "au": 0.04178,
    "per": 3.6001,
    "kind": "hot rocky planet",
    "massE": 0.037,
    "tempK": 938
   },
   {
    "key": "c",
    "name": "Kepler-444 c",
    "rE": 0.497,
    "au": 0.04881,
    "per": 4.5459,
    "kind": "hot rocky planet",
    "massE": 0.079,
    "tempK": 868
   },
   {
    "key": "d",
    "name": "Kepler-444 d",
    "rE": 0.53,
    "au": 0.06,
    "per": 6.1894,
    "kind": "hot rocky planet",
    "massE": 0.2,
    "tempK": 783
   },
   {
    "key": "e",
    "name": "Kepler-444 e",
    "rE": 0.546,
    "au": 0.0696,
    "per": 7.7435,
    "kind": "hot rocky planet",
    "massE": 0.1,
    "tempK": 727
   },
   {
    "key": "f",
    "name": "Kepler-444 f",
    "rE": 0.741,
    "au": 0.0811,
    "per": 9.7405,
    "kind": "hot rocky planet",
    "massE": 0.332,
    "tempK": 673
   }
  ]
 },
 {
  "pack": "Kepler_47",
  "star": "Kepler-47",
  "ra": 19.6865,
  "dec": 46.9204,
  "ly": 3343.168,
  "tempK": 5636,
  "spec": "—",
  "rSun": 0.936,
  "col": 16773346,
  "pulsar": false,
  "kindStar": "Sun-like G-type star",
  "pbr": true,
  "planets": [
   {
    "key": "b",
    "name": "Kepler-47 b",
    "rE": 3.05,
    "au": 0.2877,
    "per": 49.4643,
    "kind": "super-earth",
    "massE": 2.07,
    "tempK": 490
   },
   {
    "key": "d",
    "name": "Kepler-47 d",
    "rE": 7.04,
    "au": 0.6992,
    "per": 187.366,
    "kind": "super-earth",
    "massE": 19.02,
    "tempK": 314
   },
   {
    "key": "c",
    "name": "Kepler-47 c",
    "rE": 4.65,
    "au": 0.9638,
    "per": 303.227,
    "kind": "super-earth",
    "massE": 3.17,
    "tempK": 268
   }
  ]
 },
 {
  "pack": "Kepler_51",
  "star": "Kepler-51",
  "ra": 19.7653,
  "dec": 49.9376,
  "ly": 2556.515,
  "tempK": 6018,
  "spec": "—",
  "rSun": 0.94,
  "col": 16774893,
  "pulsar": false,
  "kindStar": "yellow-white F-type star",
  "pbr": true,
  "planets": [
   {
    "key": "b",
    "name": "Kepler-51 b",
    "rE": 7.1,
    "au": 0.2514,
    "per": 45.154,
    "kind": "super-puff low-density sub-neptune",
    "massE": 2.1,
    "tempK": 543
   },
   {
    "key": "c",
    "name": "Kepler-51 c",
    "rE": 9,
    "au": 0.384,
    "per": 85.312,
    "kind": "super-puff low-density sub-neptune",
    "massE": 4,
    "tempK": 439
   },
   {
    "key": "d",
    "name": "Kepler-51 d",
    "rE": 9.7,
    "au": 0.509,
    "per": 130.194,
    "kind": "super-puff low-density sub-neptune",
    "massE": 7.6,
    "tempK": 381
   },
   {
    "key": "e",
    "name": "Kepler-51 e",
    "rE": 2.18,
    "au": 0.05,
    "per": 264.284,
    "kind": "super-earth",
    "massE": 5.4,
    "tempK": null
   }
  ]
 },
 {
  "pack": "Kepler_62",
  "star": "Kepler-62",
  "ra": 18.8808,
  "dec": 45.3497,
  "ly": 981.32,
  "tempK": 4925,
  "spec": "K2 V",
  "rSun": 0.64,
  "col": 16769995,
  "pulsar": false,
  "kindStar": "orange K-type dwarf (main sequence)",
  "pbr": true,
  "planets": [
   {
    "key": "b",
    "name": "Kepler-62 b",
    "rE": 1.31,
    "au": 0.0553,
    "per": 5.7149,
    "kind": "hot rocky planet",
    "massE": 9,
    "tempK": 750
   },
   {
    "key": "c",
    "name": "Kepler-62 c",
    "rE": 0.54,
    "au": 0.0929,
    "per": 12.4417,
    "kind": "rocky terrestrial or super-earth candidate",
    "massE": 4,
    "tempK": 578
   },
   {
    "key": "d",
    "name": "Kepler-62 d",
    "rE": 1.95,
    "au": 0.12,
    "per": 18.1641,
    "kind": "super-earth",
    "massE": 14,
    "tempK": 510
   },
   {
    "key": "e",
    "name": "Kepler-62 e",
    "rE": 1.61,
    "au": 0.427,
    "per": 122.3874,
    "kind": "habitable-zone rocky",
    "massE": 36,
    "tempK": 270
   },
   {
    "key": "f",
    "name": "Kepler-62 f",
    "rE": 1.41,
    "au": 0.718,
    "per": 267.291,
    "kind": "cool habitable-zone rocky",
    "massE": 35,
    "tempK": 208
   }
  ]
 },
 {
  "pack": "Kepler_69",
  "star": "Kepler-69",
  "ra": 19.5507,
  "dec": 44.8689,
  "ly": 2382.98,
  "tempK": 5638,
  "spec": "G4 V",
  "rSun": 0.93,
  "col": 16773346,
  "pulsar": false,
  "kindStar": "Sun-like G-type star (main sequence)",
  "pbr": true,
  "planets": [
   {
    "key": "b",
    "name": "Kepler-69 b",
    "rE": 2.24,
    "au": 0.094,
    "per": 13.7223,
    "kind": "super-earth",
    "massE": 5.65,
    "tempK": 779
   },
   {
    "key": "c",
    "name": "Kepler-69 c",
    "rE": 1.71,
    "au": 0.64,
    "per": 242.4613,
    "kind": "warm super-earth",
    "massE": 3.57,
    "tempK": 299
   }
  ]
 },
 {
  "pack": "KOI_351",
  "star": "KOI-351",
  "ra": 18.9622,
  "dec": 49.3051,
  "ly": 2766.635,
  "tempK": 6080,
  "spec": "—",
  "rSun": 1.2,
  "col": 16775151,
  "pulsar": false,
  "kindStar": "yellow-white F-type star",
  "pbr": true,
  "planets": [
   {
    "key": "b",
    "name": "KOI-351 b",
    "rE": 1.31,
    "au": 0.074,
    "per": 7.0082,
    "kind": "hot irradiated rocky super-earth candidate",
    "massE": 2.27,
    "tempK": 1062
   },
   {
    "key": "c",
    "name": "KOI-351 c",
    "rE": 1.19,
    "au": 0.089,
    "per": 8.7194,
    "kind": "hot irradiated rocky super-earth candidate",
    "massE": 1.81,
    "tempK": 987
   },
   {
    "key": "i",
    "name": "Kepler-90 i",
    "rE": 1.32,
    "au": 0.12014,
    "per": 14.4491,
    "kind": "hot irradiated rocky super-earth candidate",
    "massE": 2.3,
    "tempK": 709
   },
   {
    "key": "d",
    "name": "KOI-351 d",
    "rE": 2.87,
    "au": 0.32,
    "per": 59.7367,
    "kind": "super-earth",
    "massE": 8.6,
    "tempK": 520
   },
   {
    "key": "e",
    "name": "KOI-351 e",
    "rE": 2.66,
    "au": 0.42,
    "per": 91.9391,
    "kind": "super-earth",
    "massE": 7.56,
    "tempK": 450
   },
   {
    "key": "f",
    "name": "KOI-351 f",
    "rE": 2.88,
    "au": 0.48,
    "per": 124.9144,
    "kind": "super-earth",
    "massE": 8.65,
    "tempK": 407
   },
   {
    "key": "g",
    "name": "KOI-351 g",
    "rE": 7.718,
    "au": 0.71704,
    "per": 210.7351,
    "kind": "low-density gas-rich sub-saturn",
    "massE": 15,
    "tempK": 342
   },
   {
    "key": "h",
    "name": "KOI-351 h",
    "rE": 11.252,
    "au": 0.97062,
    "per": 331.603,
    "kind": "temperate transiting gas giant",
    "massE": 203,
    "tempK": 294
   }
  ]
 },
 {
  "pack": "LHS_1140",
  "star": "LHS 1140",
  "ra": 0.7499,
  "dec": -15.2741,
  "ly": 48.878,
  "tempK": 3096,
  "spec": "M4.5 V",
  "rSun": 0.216,
  "col": 16757876,
  "pulsar": false,
  "kindStar": "red-dwarf star (main sequence)",
  "pbr": true,
  "planets": [
   {
    "key": "c",
    "name": "LHS 1140 c",
    "rE": 1.272,
    "au": 0.027,
    "per": 3.7779,
    "kind": "warm rocky terrestrial planet",
    "massE": 1.91,
    "tempK": 422
   },
   {
    "key": "b",
    "name": "LHS 1140 b",
    "rE": 1.73,
    "au": 0.0946,
    "per": 24.7372,
    "kind": "cold rocky",
    "massE": 5.6,
    "tempK": 226
   }
  ]
 },
 {
  "pack": "LP_890_9",
  "star": "LP 890-9",
  "ra": 4.2754,
  "dec": -28.3158,
  "ly": 105.772,
  "tempK": 2850,
  "spec": "M6 V",
  "rSun": 0.156,
  "col": 16755811,
  "pulsar": false,
  "kindStar": "red-dwarf star (main sequence)",
  "pbr": true,
  "planets": [
   {
    "key": "b",
    "name": "LP 890-9 b",
    "rE": 1.32,
    "au": 0.01875,
    "per": 2.7299,
    "kind": "warm inner rocky terrestrial planet",
    "massE": 13.2,
    "tempK": 396
   },
   {
    "key": "c",
    "name": "LP 890-9 c",
    "rE": 1.367,
    "au": 0.03984,
    "per": 8.4575,
    "kind": "temperate habitable-zone rocky terrestrial candidate",
    "massE": 25.3,
    "tempK": 272
   }
  ]
 },
 {
  "pack": "L_98-59",
  "star": "L 98-59",
  "ra": 8.3022,
  "dec": -68.3145,
  "ly": 34.636,
  "tempK": 3415,
  "spec": "M3 V",
  "rSun": 0.316,
  "col": 16760456,
  "pulsar": false,
  "kindStar": "red-dwarf star (main sequence)",
  "pbr": true,
  "planets": [
   {
    "key": "b",
    "name": "L 98-59 b",
    "rE": 0.837,
    "au": 0.0223,
    "per": 2.2531,
    "kind": "hot volcanic compact rocky planet",
    "massE": 0.46,
    "tempK": 620
   },
   {
    "key": "c",
    "name": "L 98-59 c",
    "rE": 1.329,
    "au": 0.0309,
    "per": 3.6907,
    "kind": "hot rocky super-earth",
    "massE": 2,
    "tempK": 526
   },
   {
    "key": "d",
    "name": "L 98-59 d",
    "rE": 1.627,
    "au": 0.0494,
    "per": 7.4507,
    "kind": "sulfur-rich volatile molten super-earth with magma-ocean interior",
    "massE": 1.64,
    "tempK": 416
   },
   {
    "key": "e",
    "name": "L 98-59 e",
    "rE": 1.49,
    "au": 0.0712,
    "per": 12.8278,
    "kind": "cool non-transiting super-earth",
    "massE": 2.82,
    "tempK": 347
   },
   {
    "key": "f",
    "name": "L 98-59 f",
    "rE": 1.48,
    "au": 0.1052,
    "per": 23.064,
    "kind": "temperate habitable-zone super-earth",
    "massE": 2.8,
    "tempK": 285
   }
  ]
 },
 {
  "pack": "PDS_70",
  "star": "PDS 70",
  "ra": 14.1361,
  "dec": -41.398,
  "ly": 368.765,
  "tempK": 4109,
  "spec": "K7",
  "rSun": 1.26,
  "col": 16765099,
  "pulsar": false,
  "kindStar": "orange K-type dwarf",
  "pbr": true,
  "planets": [
   {
    "key": "b",
    "name": "PDS 70 b",
    "rE": 21.97,
    "au": 20.8,
    "per": 43500,
    "kind": "young directly imaged accreting gas-giant protoplanet",
    "massE": 1017.051,
    "tempK": 1392
   },
   {
    "key": "c",
    "name": "PDS 70 c",
    "rE": 22.194,
    "au": 34.3,
    "per": 10,
    "kind": "young directly imaged accreting gas-giant protoplanet with circumplanetary disk evidence",
    "massE": 2383.713,
    "tempK": 1054
   }
  ]
 },
 {
  "pack": "Proxima_Cen",
  "star": "Proxima Cen",
  "ra": 14.4929,
  "dec": -62.6762,
  "ly": 4.244,
  "tempK": 2900,
  "spec": "M5.5 V",
  "rSun": 0.141,
  "col": 16756327,
  "pulsar": false,
  "kindStar": "red-dwarf star (main sequence)",
  "pbr": true,
  "planets": [
   {
    "key": "d",
    "name": "Proxima Cen d",
    "rE": 0.692,
    "au": 0.02881,
    "per": 5.1234,
    "kind": "close-in warm sub-earth rocky planet",
    "massE": 0.26,
    "tempK": 282
   },
   {
    "key": "b",
    "name": "Proxima Cen b",
    "rE": 1.02,
    "au": 0.04848,
    "per": 11.1846,
    "kind": "temperate habitable-zone rocky earth-mass planet candidate",
    "massE": 1.055,
    "tempK": 218
   }
  ]
 },
 {
  "pack": "Ross_128",
  "star": "Ross 128",
  "ra": 11.7958,
  "dec": 0.7993,
  "ly": 11.006,
  "tempK": 3192,
  "spec": "M4",
  "rSun": 0.197,
  "col": 16758651,
  "pulsar": false,
  "kindStar": "red-dwarf star",
  "pbr": true,
  "planets": [
   {
    "key": "b",
    "name": "Ross 128 b",
    "rE": 1.11,
    "au": 0.0496,
    "per": 9.8658,
    "kind": "temperate inner-edge habitable-zone rocky super-earth candidate",
    "massE": 1.4,
    "tempK": 301
   }
  ]
 },
 {
  "pack": "Teegarden_s_Star",
  "star": "Teegarden's Star",
  "ra": 2.8846,
  "dec": 16.8649,
  "ly": 12.494,
  "tempK": 3034,
  "spec": "M7.0 V",
  "rSun": 0.12,
  "col": 16757360,
  "pulsar": false,
  "kindStar": "red-dwarf star (main sequence)",
  "pbr": true,
  "planets": [
   {
    "key": "b",
    "name": "Teegarden's Star b",
    "rE": 1.05,
    "au": 0.0259,
    "per": 4.9063,
    "kind": "temperate habitable-zone rocky super-earth",
    "massE": 1.16,
    "tempK": 277
   },
   {
    "key": "c",
    "name": "Teegarden's Star c",
    "rE": 1.02,
    "au": 0.0455,
    "per": 11.416,
    "kind": "cool outer habitable-zone rocky super-earth",
    "massE": 1.05,
    "tempK": 209
   },
   {
    "key": "d",
    "name": "Teegarden's Star d",
    "rE": 0.954,
    "au": 0.0791,
    "per": 26.13,
    "kind": "cold outer rocky sub-earth",
    "massE": 0.82,
    "tempK": 159
   }
  ]
 },
 {
  "pack": "TOI-178",
  "star": "TOI-178",
  "ra": 0.4868,
  "dec": -30.4541,
  "ly": 204.497,
  "tempK": 4316,
  "spec": "K",
  "rSun": 0.662,
  "col": 16766388,
  "pulsar": false,
  "kindStar": "orange K-type dwarf",
  "pbr": true,
  "planets": [
   {
    "key": "b",
    "name": "TOI-178 b",
    "rE": 1.2,
    "au": 0.02607,
    "per": 1.9146,
    "kind": "very hot rocky super-earth",
    "massE": 0.96,
    "tempK": 1040
   },
   {
    "key": "c",
    "name": "TOI-178 c",
    "rE": 1.754,
    "au": 0.037,
    "per": 3.2385,
    "kind": "hot dense rocky super-earth",
    "massE": 4.64,
    "tempK": 873
   },
   {
    "key": "d",
    "name": "TOI-178 d",
    "rE": 2.695,
    "au": 0.0592,
    "per": 6.5576,
    "kind": "hot low-density volatile-rich sub-neptune",
    "massE": 5.2,
    "tempK": 690
   },
   {
    "key": "e",
    "name": "TOI-178 e",
    "rE": 2.301,
    "au": 0.0783,
    "per": 9.9632,
    "kind": "warm low-density volatile-rich sub-neptune",
    "massE": 3.48,
    "tempK": 600
   },
   {
    "key": "f",
    "name": "TOI-178 f",
    "rE": 2.417,
    "au": 0.1039,
    "per": 15.2333,
    "kind": "warm sub-neptune with moderate volatile envelope",
    "massE": 5.63,
    "tempK": 521
   },
   {
    "key": "g",
    "name": "TOI-178 g",
    "rE": 2.939,
    "au": 0.1275,
    "per": 20.7166,
    "kind": "cool-warm very low-density puffy sub-neptune",
    "massE": 4.4,
    "tempK": 470
   }
  ]
 },
 {
  "pack": "TOI-700",
  "star": "TOI-700",
  "ra": 6.473,
  "dec": -65.5786,
  "ly": 101.521,
  "tempK": 3459,
  "spec": "M2.5 V",
  "rSun": 0.421,
  "col": 16760715,
  "pulsar": false,
  "kindStar": "red-dwarf star (main sequence)",
  "pbr": true,
  "planets": [
   {
    "key": "b",
    "name": "TOI-700 b",
    "rE": 0.914,
    "au": 0.0677,
    "per": 9.9772,
    "kind": "warm inner terrestrial planet",
    "massE": 0.704,
    "tempK": 417
   },
   {
    "key": "c",
    "name": "TOI-700 c",
    "rE": 2.6,
    "au": 0.0929,
    "per": 16.0511,
    "kind": "warm volatile-rich sub-neptune",
    "massE": 7.27,
    "tempK": 356
   },
   {
    "key": "e",
    "name": "TOI-700 e",
    "rE": 0.953,
    "au": 0.134,
    "per": 27.8098,
    "kind": "inner-edge habitable-zone rocky earth-size planet",
    "massE": 0.818,
    "tempK": 273
   },
   {
    "key": "d",
    "name": "TOI-700 d",
    "rE": 1.073,
    "au": 0.1633,
    "per": 37.424,
    "kind": "outer habitable-zone rocky earth-size planet",
    "massE": 1.25,
    "tempK": 269
   }
  ]
 },
 {
  "pack": "TOI_270",
  "star": "TOI-270",
  "ra": 4.5611,
  "dec": -51.9574,
  "ly": 73.318,
  "tempK": 3506,
  "spec": "M3 V",
  "rSun": 0.38,
  "col": 16761229,
  "pulsar": false,
  "kindStar": "red-dwarf star (main sequence)",
  "pbr": true,
  "planets": [
   {
    "key": "b",
    "name": "TOI-270 b",
    "rE": 1.28,
    "au": 0.03197,
    "per": 3.3599,
    "kind": "warm rocky terrestrial planet",
    "massE": 1.48,
    "tempK": 600
   },
   {
    "key": "c",
    "name": "TOI-270 c",
    "rE": 2.33,
    "au": 0.04526,
    "per": 5.6605,
    "kind": "warm volatile-rich sub-neptune",
    "massE": 6.2,
    "tempK": 489
   },
   {
    "key": "d",
    "name": "TOI-270 d",
    "rE": 2,
    "au": 0.0721,
    "per": 11.3819,
    "kind": "cool-warm volatile-rich sub-neptune",
    "massE": 4.2,
    "tempK": 383
   }
  ]
 },
 {
  "pack": "TRAPPIST-1",
  "star": "TRAPPIST-1",
  "ra": 23.1084,
  "dec": -5.0435,
  "ly": 40.541,
  "tempK": 2566,
  "spec": "M8.0 V",
  "rSun": 0.119,
  "col": 16753228,
  "pulsar": false,
  "kindStar": "red-dwarf star (main sequence)",
  "pbr": true,
  "planets": [
   {
    "key": "b",
    "name": "TRAPPIST-1 b",
    "rE": 1.116,
    "au": 0.05,
    "per": 10,
    "kind": "very hot irradiated rocky inner planet",
    "massE": 1.374,
    "tempK": 398
   },
   {
    "key": "c",
    "name": "TRAPPIST-1 c",
    "rE": 1.097,
    "au": 0.05,
    "per": 10,
    "kind": "hot rocky inner planet",
    "massE": 1.308,
    "tempK": 340
   },
   {
    "key": "d",
    "name": "TRAPPIST-1 d",
    "rE": 0.788,
    "au": 0.05,
    "per": 10,
    "kind": "warm temperate rocky planet",
    "massE": 0.388,
    "tempK": 286
   },
   {
    "key": "e",
    "name": "TRAPPIST-1 e",
    "rE": 0.92,
    "au": 0.05,
    "per": 10,
    "kind": "cool temperate rocky habitable-zone candidate",
    "massE": 0.692,
    "tempK": 250
   },
   {
    "key": "f",
    "name": "TRAPPIST-1 f",
    "rE": 1.045,
    "au": 0.05,
    "per": 10,
    "kind": "cold rocky",
    "massE": 1.039,
    "tempK": 218
   },
   {
    "key": "g",
    "name": "TRAPPIST-1 g",
    "rE": 1.129,
    "au": 0.05,
    "per": 10,
    "kind": "cold outer rocky",
    "massE": 1.321,
    "tempK": 197
   },
   {
    "key": "h",
    "name": "TRAPPIST-1 h",
    "rE": 0.755,
    "au": 0.05,
    "per": 10,
    "kind": "frigid outer rocky",
    "massE": 0.326,
    "tempK": 172
   }
  ]
 },
 {
  "pack": "WASP_121",
  "star": "WASP-121",
  "ra": 7.1733,
  "dec": -39.0973,
  "ly": 880.29,
  "tempK": 6628,
  "spec": "F6 V",
  "rSun": 1.461,
  "col": 16776191,
  "pulsar": false,
  "kindStar": "yellow-white F-type star (main sequence)",
  "pbr": true,
  "planets": [
   {
    "key": "b",
    "name": "WASP-121 b",
    "rE": 19.526,
    "au": 0.02571,
    "per": 1.2749,
    "kind": "ultra-hot inflated hot jupiter with escaping atmosphere",
    "massE": 371.859,
    "tempK": 2409
   }
  ]
 },
 {
  "pack": "WASP_12",
  "star": "WASP-12",
  "ra": 6.5091,
  "dec": 29.6723,
  "ly": 1393.49,
  "tempK": 6265,
  "spec": "—",
  "rSun": 1.69,
  "col": 16775924,
  "pulsar": false,
  "kindStar": "yellow-white F-type star",
  "pbr": true,
  "planets": [
   {
    "key": "b",
    "name": "WASP-12 b",
    "rE": 22.026,
    "au": 0.0234,
    "per": 1.0914,
    "kind": "ultra-hot inflated tidally distorted hot jupiter",
    "massE": 467.21,
    "tempK": 2601
   }
  ]
 },
 {
  "pack": "WASP_47",
  "star": "WASP-47",
  "ra": 22.0802,
  "dec": -12.0191,
  "ly": 863.597,
  "tempK": 5565,
  "spec": "G9",
  "rSun": 1.156,
  "col": 16773088,
  "pulsar": false,
  "kindStar": "Sun-like G-type star",
  "pbr": true,
  "planets": [
   {
    "key": "e",
    "name": "WASP-47 e",
    "rE": 1.83,
    "au": 0.01673,
    "per": 0.7896,
    "kind": "ultra-hot dense rocky super-earth",
    "massE": 9,
    "tempK": 1992
   },
   {
    "key": "b",
    "name": "WASP-47 b",
    "rE": 12.86,
    "au": 0.052,
    "per": 4.1592,
    "kind": "close-in hot jupiter gas giant",
    "massE": 374,
    "tempK": 1275
   },
   {
    "key": "d",
    "name": "WASP-47 d",
    "rE": 3.65,
    "au": 0.085,
    "per": 9.0305,
    "kind": "hot volatile-rich neptune",
    "massE": 15.5,
    "tempK": 885
   },
   {
    "key": "c",
    "name": "WASP-47 c",
    "rE": 11.2,
    "au": 1.393,
    "per": 589.57,
    "kind": "cool outer jovian gas giant",
    "massE": 447,
    "tempK": 247
   }
  ]
 },
 {
  "pack": "Wolf_1061",
  "star": "Wolf 1061",
  "ra": 16.505,
  "dec": -12.6677,
  "ly": 14.044,
  "tempK": 3342,
  "spec": "M3.5",
  "rSun": 0.307,
  "col": 16759940,
  "pulsar": false,
  "kindStar": "red-dwarf star",
  "pbr": true,
  "planets": [
   {
    "key": "b",
    "name": "Wolf 1061 b",
    "rE": 1.21,
    "au": 0.0375,
    "per": 4.8869,
    "kind": "hot inner rocky super-earth",
    "massE": 1.91,
    "tempK": 461
   },
   {
    "key": "c",
    "name": "Wolf 1061 c",
    "rE": 1.66,
    "au": 0.089,
    "per": 17.8719,
    "kind": "warm rocky super-earth near inner habitable zone",
    "massE": 3.41,
    "tempK": 299
   },
   {
    "key": "d",
    "name": "Wolf 1061 d",
    "rE": 2.69,
    "au": 0.47,
    "per": 217.21,
    "kind": "cold volatile-rich outer super-earth",
    "massE": 7.7,
    "tempK": 130
   }
  ]
 },
 {
  "pack": "YZ_Cet",
  "star": "YZ Cet",
  "ra": 1.2089,
  "dec": -16.9962,
  "ly": 12.107,
  "tempK": 3151,
  "spec": "M4.5 V",
  "rSun": 0.157,
  "col": 16758392,
  "pulsar": false,
  "kindStar": "red-dwarf star (main sequence)",
  "pbr": true,
  "planets": [
   {
    "key": "b",
    "name": "YZ Cet b",
    "rE": 0.913,
    "au": 0.01634,
    "per": 2.0209,
    "kind": "very hot inner rocky terrestrial planet",
    "massE": 0.7,
    "tempK": 471
   },
   {
    "key": "c",
    "name": "YZ Cet c",
    "rE": 1.05,
    "au": 0.02156,
    "per": 3.0599,
    "kind": "hot rocky terrestrial planet",
    "massE": 1.14,
    "tempK": 410
   },
   {
    "key": "d",
    "name": "YZ Cet d",
    "rE": 1.03,
    "au": 0.02851,
    "per": 4.6563,
    "kind": "warm close-in rocky terrestrial planet",
    "massE": 1.09,
    "tempK": 357
   }
  ]
 }
];
export default EXO_SYSTEMS;
