/* CELESTIUM — EXOPLANET SYSTEMS (data). 46 real systems at their
   true J2000 sky positions. Physical truth (radii, masses, orbits, periods,
   temperatures) from the per-system scientific model packs (NASA Exoplanet
   Archive pscomppars); sky position (RA/Dec) + distance + spectral type from the
   same archive. Star colour derived from effective temperature (blackbody).
   GENERATED by scripts/build-exo.mjs — edit the packs/script, not this file. */
export interface ExoPlanet { key: string; name: string; rE: number; au: number; per: number; kind: string; massE: number | null; tempK: number | null; }
export interface ExoSystem { pack: string; star: string; ra: number; dec: number; ly: number; tempK: number | null; spec: string; rSun: number; col: number; pulsar: boolean; kindStar: string; pbr?: boolean; planets: ExoPlanet[]; }
const EXO_SYSTEMS: ExoSystem[] = [
 {
  "pack": "Proxima_Centauri",
  "star": "Proxima Cen",
  "ra": 14.4956,
  "dec": -62.676,
  "ly": 4.247,
  "tempK": 2900,
  "spec": "M5.5 V",
  "rSun": 0.141,
  "col": 16748382,
  "pulsar": false,
  "kindStar": "M-type main-sequence star",
  "planets": [
   {
    "key": "d",
    "name": "Proxima Cen d",
    "rE": 0.7,
    "au": 0.0288,
    "per": 5.12,
    "kind": "temperate rocky planet",
    "massE": 0.26,
    "tempK": 282
   },
   {
    "key": "b",
    "name": "Proxima Cen b",
    "rE": 1,
    "au": 0.048,
    "per": 11.19,
    "kind": "cold rocky planet",
    "massE": 1,
    "tempK": 216
   }
  ],
  "pbr": false
 },
 {
  "pack": "Kepler-62",
  "star": "Kepler-62",
  "ra": 18.879,
  "dec": 45.349,
  "ly": 980,
  "tempK": 4925,
  "spec": "K2 V",
  "rSun": 0.639,
  "col": 16767392,
  "pulsar": false,
  "kindStar": "K-type main-sequence star",
  "planets": [
   {
    "key": "b",
    "name": "Kepler-62 b",
    "rE": 1.31,
    "au": 0.0553,
    "per": 5.71,
    "kind": "warm rocky planet",
    "massE": 9,
    "tempK": 750
   },
   {
    "key": "c",
    "name": "Kepler-62 c",
    "rE": 0.54,
    "au": 0.0929,
    "per": 12.44,
    "kind": "warm rocky planet",
    "massE": 4,
    "tempK": 578
   },
   {
    "key": "d",
    "name": "Kepler-62 d",
    "rE": 1.95,
    "au": 0.12,
    "per": 18.16,
    "kind": "sub-Neptune / volatile-rich mini-Neptune",
    "massE": 14,
    "tempK": 510
   },
   {
    "key": "e",
    "name": "Kepler-62 e",
    "rE": 1.61,
    "au": 0.427,
    "per": 122.39,
    "kind": "temperate rocky planet",
    "massE": 36,
    "tempK": 270
   },
   {
    "key": "f",
    "name": "Kepler-62 f",
    "rE": 1.41,
    "au": 0.718,
    "per": 267.29,
    "kind": "cold rocky planet",
    "massE": 35,
    "tempK": 208
   }
  ],
  "pbr": false
 },
 {
  "pack": "Kepler-452",
  "star": "Kepler-452",
  "ra": 19.7442,
  "dec": 44.278,
  "ly": 1810,
  "tempK": 5578,
  "spec": "",
  "rSun": 0.793,
  "col": 16773846,
  "pulsar": false,
  "kindStar": "K-type main-sequence star",
  "planets": [
   {
    "key": "b",
    "name": "Kepler-452 b",
    "rE": 1.13,
    "au": 0.9892,
    "per": 384.84,
    "kind": "cold rocky planet",
    "massE": null,
    "tempK": 220
   }
  ],
  "pbr": false
 },
 {
  "pack": "TOI-700",
  "star": "TOI-700",
  "ra": 6.444,
  "dec": -65.578,
  "ly": 101,
  "tempK": 3461,
  "spec": "",
  "rSun": 0.424,
  "col": 16748382,
  "pulsar": false,
  "kindStar": "ultra-cool dwarf star",
  "planets": [
   {
    "key": "b",
    "name": "TOI-700 b",
    "rE": 1.04,
    "au": 0.0677,
    "per": 9.98,
    "kind": "warm rocky planet",
    "massE": null,
    "tempK": 417
   },
   {
    "key": "c",
    "name": "TOI-700 c",
    "rE": 2.65,
    "au": 0.0929,
    "per": 16.05,
    "kind": "sub-Neptune / volatile-rich mini-Neptune",
    "massE": null,
    "tempK": 356
   },
   {
    "key": "e",
    "name": "TOI-700 e",
    "rE": 0.95,
    "au": 0.134,
    "per": 27.81,
    "kind": "rocky exoplanet",
    "massE": null,
    "tempK": null
   },
   {
    "key": "d",
    "name": "TOI-700 d",
    "rE": 1.14,
    "au": 0.1633,
    "per": 37.42,
    "kind": "temperate rocky planet",
    "massE": null,
    "tempK": 268.8
   }
  ],
  "pbr": false
 },
 {
  "pack": "LHS_1140",
  "star": "LHS 1140",
  "ra": 0.73,
  "dec": -15.271,
  "ly": 48.9,
  "tempK": 3216,
  "spec": "",
  "rSun": 0.214,
  "col": 16748382,
  "pulsar": false,
  "kindStar": "ultra-cool dwarf star",
  "planets": [
   {
    "key": "c",
    "name": "LHS 1140 c",
    "rE": 1.28,
    "au": 0.0267,
    "per": 3.78,
    "kind": "warm rocky planet",
    "massE": 1.81,
    "tempK": 438
   },
   {
    "key": "b",
    "name": "LHS 1140 b",
    "rE": 1.43,
    "au": 0.0875,
    "per": 24.74,
    "kind": "temperate rocky planet",
    "massE": 6.65,
    "tempK": 230
   }
  ],
  "pbr": false
 },
 {
  "pack": "Teegardens_Star",
  "star": "Teegarden's Star",
  "ra": 2.8917,
  "dec": 16.88,
  "ly": 12.5,
  "tempK": 3034,
  "spec": "",
  "rSun": 0.12,
  "col": 16748382,
  "pulsar": false,
  "kindStar": "ultra-cool dwarf star",
  "planets": [
   {
    "key": "b",
    "name": "Teegarden's Star b",
    "rE": 1.04,
    "au": 0.0259,
    "per": 4.91,
    "kind": "temperate rocky planet",
    "massE": 1.16,
    "tempK": 277
   },
   {
    "key": "c",
    "name": "Teegarden's Star c",
    "rE": 1.01,
    "au": 0.0455,
    "per": 11.42,
    "kind": "cold rocky planet",
    "massE": 1.05,
    "tempK": 209
   },
   {
    "key": "d",
    "name": "Teegarden's Star d",
    "rE": 0.95,
    "au": 0.0791,
    "per": 26.13,
    "kind": "rocky exoplanet",
    "massE": 0.82,
    "tempK": 159
   }
  ],
  "pbr": false
 },
 {
  "pack": "Fomalhaut",
  "star": "Fomalhaut",
  "ra": 22.9608,
  "dec": -29.622,
  "ly": 25.1,
  "tempK": 8590,
  "spec": "A3 V",
  "rSun": 1.829,
  "col": 15265535,
  "pulsar": false,
  "kindStar": "A-type main-sequence star",
  "planets": [
   {
    "key": "b",
    "name": "Fomalhaut b",
    "rE": 5.5,
    "au": 115,
    "per": 874666,
    "kind": "gas giant / directly imaged planet",
    "massE": 1000,
    "tempK": 290
   }
  ],
  "pbr": false
 },
 {
  "pack": "PDS_70",
  "star": "PDS 70",
  "ra": 14.1373,
  "dec": -41.403,
  "ly": 370,
  "tempK": 3972,
  "spec": "",
  "rSun": 0.6,
  "col": 16767392,
  "pulsar": false,
  "kindStar": "M-type main-sequence star",
  "planets": [
   {
    "key": "b",
    "name": "PDS 70 b",
    "rE": 30.49,
    "au": 20,
    "per": 42175.44,
    "kind": "gas giant",
    "massE": 953.49,
    "tempK": 1204
   },
   {
    "key": "c",
    "name": "PDS 70 c",
    "rE": 22.87,
    "au": 34,
    "per": 93483.07,
    "kind": "gas giant",
    "massE": 635.66,
    "tempK": 995
   }
  ],
  "pbr": false
 },
 {
  "pack": "Upsilon_Andromedae",
  "star": "ups And",
  "ra": 1.6171,
  "dec": 41.406,
  "ly": 44,
  "tempK": 6200,
  "spec": "F8 V",
  "rSun": 1.25,
  "col": 16774378,
  "pulsar": false,
  "kindStar": "F-type main-sequence star",
  "planets": [
   {
    "key": "b",
    "name": "ups And b",
    "rE": 11,
    "au": 0.057,
    "per": 4.61,
    "kind": "gas giant",
    "massE": 216.1244,
    "tempK": null
   },
   {
    "key": "c",
    "name": "ups And c",
    "rE": 11,
    "au": 0.821,
    "per": 238.1,
    "kind": "gas giant",
    "massE": 715.09,
    "tempK": null
   },
   {
    "key": "d",
    "name": "ups And d",
    "rE": 11,
    "au": 2.51,
    "per": 1274.6,
    "kind": "gas giant",
    "massE": 1255.38,
    "tempK": null
   }
  ],
  "pbr": false
 },
 {
  "pack": "WASP-12",
  "star": "WASP-12",
  "ra": 6.5085,
  "dec": 29.672,
  "ly": 1410,
  "tempK": 6250,
  "spec": "",
  "rSun": 1.618,
  "col": 16774378,
  "pulsar": false,
  "kindStar": "G-type main-sequence star",
  "planets": [
   {
    "key": "b",
    "name": "WASP-12 b",
    "rE": 20.46,
    "au": 0.0231,
    "per": 1.09,
    "kind": "gas giant",
    "massE": 454.4969,
    "tempK": 2523
   }
  ],
  "pbr": false
 },
 {
  "pack": "WASP-121",
  "star": "WASP-121",
  "ra": 7.1813,
  "dec": -39.097,
  "ly": 858,
  "tempK": 6459,
  "spec": "F6 V",
  "rSun": 1.457,
  "col": 16774378,
  "pulsar": false,
  "kindStar": "F-type main-sequence star",
  "planets": [
   {
    "key": "b",
    "name": "WASP-121 b",
    "rE": 20.9,
    "au": 0.0254,
    "per": 1.27,
    "kind": "gas giant",
    "massE": 375.99289,
    "tempK": 2358
   }
  ],
  "pbr": false
 },
 {
  "pack": "KELT-9",
  "star": "KELT-9",
  "ra": 20.5161,
  "dec": 39.956,
  "ly": 670,
  "tempK": 10170,
  "spec": "B9.5-A0",
  "rSun": 2.36,
  "col": 11193599,
  "pulsar": false,
  "kindStar": "B-type main-sequence star",
  "planets": [
   {
    "key": "b",
    "name": "KELT-9 b",
    "rE": 21.2,
    "au": 0.0346,
    "per": 1.48,
    "kind": "gas giant",
    "massE": 915.3504,
    "tempK": 4050
   }
  ],
  "pbr": false
 },
 {
  "pack": "PSR_B1257+12",
  "star": "PSR B1257+12",
  "ra": 13.0058,
  "dec": 12.683,
  "ly": 1955,
  "tempK": null,
  "spec": "",
  "rSun": 0.85,
  "col": 16773846,
  "pulsar": true,
  "kindStar": "main-sequence star",
  "planets": [
   {
    "key": "b",
    "name": "PSR B1257+12 b",
    "rE": 0.32,
    "au": 0.19,
    "per": 25.34,
    "kind": "pulsar-orbiting rocky planet",
    "massE": 0.015,
    "tempK": null
   },
   {
    "key": "c",
    "name": "PSR B1257+12 c",
    "rE": 1.39,
    "au": 0.36,
    "per": 66.56,
    "kind": "pulsar-orbiting rocky planet",
    "massE": 3.4,
    "tempK": null
   },
   {
    "key": "d",
    "name": "PSR B1257+12 d",
    "rE": 1.44,
    "au": 0.46,
    "per": 98.21,
    "kind": "pulsar-orbiting rocky planet",
    "massE": 3.9,
    "tempK": null
   }
  ],
  "pbr": false
 },
 {
  "pack": "47_Ursae_Majoris",
  "star": "47 UMa",
  "ra": 10.953,
  "dec": 40.431,
  "ly": 45.9,
  "tempK": 5829.16,
  "spec": "",
  "rSun": 1.135,
  "col": 16773846,
  "pulsar": false,
  "kindStar": "K-type main-sequence star",
  "planets": [
   {
    "key": "b",
    "name": "47 UMa b",
    "rE": 11,
    "au": 2.059,
    "per": 1076.6,
    "kind": "gas giant",
    "massE": 774.86565627,
    "tempK": null
   },
   {
    "key": "c",
    "name": "47 UMa c",
    "rE": 11,
    "au": 3.404,
    "per": 2287,
    "kind": "gas giant",
    "massE": 157.96071828,
    "tempK": null
   },
   {
    "key": "d",
    "name": "47 UMa d",
    "rE": 11,
    "au": 11.6,
    "per": 14002,
    "kind": "gas giant",
    "massE": 521.22,
    "tempK": null
   }
  ],
  "pbr": false
 },
 {
  "pack": "51_Peg",
  "star": "51 Pegasi",
  "ra": 22.9578,
  "dec": 20.7691,
  "ly": 50.428,
  "tempK": 5758,
  "spec": "G5V",
  "rSun": 1.176,
  "col": 16773862,
  "pulsar": false,
  "kindStar": "Sun-like G-type star (main sequence)",
  "pbr": true,
  "planets": [
   {
    "key": "b",
    "name": "51 Peg b",
    "rE": 14.3,
    "au": 0.0527,
    "per": 4.2308,
    "kind": "gas giant",
    "massE": 146.202,
    "tempK": 1311
   }
  ]
 },
 {
  "pack": "55_Cnc",
  "star": "55 Cancri",
  "ra": 8.8765,
  "dec": 28.3298,
  "ly": 41.048,
  "tempK": 5172,
  "spec": "G8 V",
  "rSun": 0.943,
  "col": 16771028,
  "pulsar": false,
  "kindStar": "Sun-like G-type star (main sequence)",
  "pbr": true,
  "planets": [
   {
    "key": "e",
    "name": "55 Cnc e",
    "rE": 1.875,
    "au": 0.01544,
    "per": 0.7365,
    "kind": "ultra-hot rocky super-earth",
    "massE": 7.99,
    "tempK": 1958
   },
   {
    "key": "b",
    "name": "55 Cnc b",
    "rE": 13.9,
    "au": 0.118,
    "per": 14.6516,
    "kind": "gas giant",
    "massE": 263.978,
    "tempK": 700
   },
   {
    "key": "c",
    "name": "55 Cnc c",
    "rE": 8.51,
    "au": 0.247,
    "per": 44.3936,
    "kind": "gas giant",
    "massE": 54.474,
    "tempK": 499
   },
   {
    "key": "f",
    "name": "55 Cnc f",
    "rE": 7.59,
    "au": 0.802,
    "per": 260.58,
    "kind": "super-earth",
    "massE": 44.812,
    "tempK": 277
   },
   {
    "key": "d",
    "name": "55 Cnc d",
    "rE": 13,
    "au": 5.6,
    "per": 4799,
    "kind": "gas giant",
    "massE": 1232.493,
    "tempK": 105
   }
  ]
 },
 {
  "pack": "AU_Mic",
  "star": "AU Microscopii",
  "ra": 20.7527,
  "dec": -31.3424,
  "ly": 31.709,
  "tempK": 3540,
  "spec": "M1 V",
  "rSun": 0.862,
  "col": 16761487,
  "pulsar": false,
  "kindStar": "red-dwarf star (main sequence)",
  "pbr": true,
  "planets": [
   {
    "key": "b",
    "name": "AU Mic b",
    "rE": 4.79,
    "au": 0.07,
    "per": 8.4634,
    "kind": "super-earth",
    "massE": 8.99,
    "tempK": 555
   },
   {
    "key": "c",
    "name": "AU Mic c",
    "rE": 2.79,
    "au": 0.119,
    "per": 18.859,
    "kind": "super-earth",
    "massE": 14.46,
    "tempK": 425
   },
   {
    "key": "d",
    "name": "AU Mic d",
    "rE": 1.02,
    "au": 0.05,
    "per": 12.736,
    "kind": "rocky terrestrial or super-earth candidate",
    "massE": 1.053,
    "tempK": null
   }
  ]
 },
 {
  "pack": "Barnard_s_star",
  "star": "Barnard's Star",
  "ra": 17.9632,
  "dec": 4.738,
  "ly": 5.957,
  "tempK": 3195,
  "spec": "M3.5-4 V",
  "rSun": 0.185,
  "col": 16758651,
  "pulsar": false,
  "kindStar": "red-dwarf star (main sequence)",
  "pbr": true,
  "planets": [
   {
    "key": "d",
    "name": "Barnard d",
    "rE": 0.694,
    "au": 0.0188,
    "per": 2.3402,
    "kind": "rocky terrestrial or super-earth candidate",
    "massE": 0.263,
    "tempK": 483
   },
   {
    "key": "b",
    "name": "Barnard b",
    "rE": 0.72,
    "au": 0.0229,
    "per": 3.1542,
    "kind": "rocky terrestrial or super-earth candidate",
    "massE": 0.299,
    "tempK": 438
   },
   {
    "key": "c",
    "name": "Barnard c",
    "rE": 0.743,
    "au": 0.0274,
    "per": 4.1244,
    "kind": "rocky terrestrial or super-earth candidate",
    "massE": 0.335,
    "tempK": 400
   },
   {
    "key": "e",
    "name": "Barnard e",
    "rE": 0.637,
    "au": 0.0381,
    "per": 6.7392,
    "kind": "rocky terrestrial or super-earth candidate",
    "massE": 0.193,
    "tempK": 340
   }
  ]
 },
 {
  "pack": "bet_Pic",
  "star": "Beta Pictoris",
  "ra": 5.7881,
  "dec": -51.0661,
  "ly": 64.397,
  "tempK": 8039,
  "spec": "A5V",
  "rSun": 1.544,
  "col": 14542335,
  "pulsar": false,
  "kindStar": "white A-type star (main sequence)",
  "pbr": true,
  "planets": [
   {
    "key": "c",
    "name": "bet Pic c",
    "rE": 12.5,
    "au": 2.68,
    "per": 1192.7795,
    "kind": "gas giant",
    "massE": 3222.462,
    "tempK": 1250
   },
   {
    "key": "b",
    "name": "bet Pic b",
    "rE": 18.495,
    "au": 10.018,
    "per": 8617.5095,
    "kind": "gas giant",
    "massE": 3727.809,
    "tempK": 1612
   }
  ]
 },
 {
  "pack": "GJ_1214",
  "star": "GJ 1214",
  "ra": 17.2554,
  "dec": 4.9607,
  "ly": 47.758,
  "tempK": 3101,
  "spec": "M4 V",
  "rSun": 0.216,
  "col": 16757877,
  "pulsar": false,
  "kindStar": "red-dwarf star (main sequence)",
  "pbr": true,
  "planets": [
   {
    "key": "b",
    "name": "GJ 1214 b",
    "rE": 2.733,
    "au": 0.01505,
    "per": 1.5804,
    "kind": "super-earth",
    "massE": 8.41,
    "tempK": 567
   }
  ]
 },
 {
  "pack": "GJ_357",
  "star": "GJ 357",
  "ra": 9.6005,
  "dec": -21.6651,
  "ly": 30.795,
  "tempK": 3505,
  "spec": "M2.5 V",
  "rSun": 0.337,
  "col": 16761229,
  "pulsar": false,
  "kindStar": "red-dwarf star (main sequence)",
  "pbr": true,
  "planets": [
   {
    "key": "b",
    "name": "GJ 357 b",
    "rE": 1.2,
    "au": 0.036,
    "per": 3.9306,
    "kind": "rocky terrestrial or super-earth candidate",
    "massE": 1.83,
    "tempK": 518
   },
   {
    "key": "c",
    "name": "GJ 357 c",
    "rE": 1.66,
    "au": 0.061,
    "per": 9.1247,
    "kind": "rocky terrestrial or super-earth candidate",
    "massE": 3.4,
    "tempK": 401
   },
   {
    "key": "d",
    "name": "GJ 357 d",
    "rE": 2.34,
    "au": 0.204,
    "per": 55.661,
    "kind": "super-earth",
    "massE": 6.1,
    "tempK": 220
   }
  ]
 },
 {
  "pack": "GJ_436",
  "star": "GJ 436",
  "ra": 11.7034,
  "dec": 26.7031,
  "ly": 31.811,
  "tempK": 3586,
  "spec": "M2.5 V",
  "rSun": 0.455,
  "col": 16761746,
  "pulsar": false,
  "kindStar": "red-dwarf star (main sequence)",
  "pbr": true,
  "planets": [
   {
    "key": "b",
    "name": "GJ 436 b",
    "rE": 4.17,
    "au": 0.0291,
    "per": 2.6439,
    "kind": "super-earth",
    "massE": 22.1,
    "tempK": 686
   }
  ]
 },
 {
  "pack": "GJ_667_C",
  "star": "GJ 667 C",
  "ra": 17.3167,
  "dec": -34.9978,
  "ly": 23.627,
  "tempK": 3350,
  "spec": "M1.5 V",
  "rSun": 1,
  "col": 16759940,
  "pulsar": false,
  "kindStar": "red-dwarf star (main sequence)",
  "pbr": true,
  "planets": [
   {
    "key": "b",
    "name": "GJ 667 C b",
    "rE": 2.25,
    "au": 0.05043,
    "per": 7.203,
    "kind": "super-earth",
    "massE": 5.68,
    "tempK": null
   },
   {
    "key": "c",
    "name": "GJ 667 C c",
    "rE": 1.77,
    "au": 0.125,
    "per": 28.14,
    "kind": "rocky terrestrial or super-earth candidate",
    "massE": 3.8,
    "tempK": null
   }
  ]
 },
 {
  "pack": "GJ_876",
  "star": "GJ 876",
  "ra": 22.8883,
  "dec": -14.2666,
  "ly": 15.248,
  "tempK": 3294,
  "spec": "M2.5V",
  "rSun": 0.3,
  "col": 16759425,
  "pulsar": false,
  "kindStar": "red-dwarf star (main sequence)",
  "pbr": true,
  "planets": [
   {
    "key": "d",
    "name": "GJ 876 d",
    "rE": 2.51,
    "au": 0.02081,
    "per": 1.9378,
    "kind": "super-earth",
    "massE": 6.83,
    "tempK": 603
   },
   {
    "key": "c",
    "name": "GJ 876 c",
    "rE": 14,
    "au": 0.12959,
    "per": 30.0881,
    "kind": "gas giant",
    "massE": 226.985,
    "tempK": 242
   },
   {
    "key": "b",
    "name": "GJ 876 b",
    "rE": 13.3,
    "au": 0.20832,
    "per": 61.1166,
    "kind": "gas giant",
    "massE": 723.223,
    "tempK": 191
   },
   {
    "key": "e",
    "name": "GJ 876 e",
    "rE": 3.92,
    "au": 0.3343,
    "per": 124.26,
    "kind": "super-earth",
    "massE": 14.6,
    "tempK": 150
   }
  ]
 },
 {
  "pack": "GJ_887",
  "star": "GJ 887",
  "ra": 23.1002,
  "dec": -35.8473,
  "ly": 10.72,
  "tempK": 3688,
  "spec": "M1 V",
  "rSun": 0.468,
  "col": 16762519,
  "pulsar": false,
  "kindStar": "red-dwarf star (main sequence)",
  "pbr": true,
  "planets": [
   {
    "key": "e",
    "name": "GJ 887 e",
    "rE": 1.12,
    "au": 0.0417,
    "per": 4.4249,
    "kind": "rocky terrestrial or super-earth candidate",
    "massE": 1.46,
    "tempK": 544
   },
   {
    "key": "b",
    "name": "GJ 887 b",
    "rE": 1.8,
    "au": 0.0683,
    "per": 9.2619,
    "kind": "super-earth",
    "massE": 3.9,
    "tempK": 426
   },
   {
    "key": "c",
    "name": "GJ 887 c",
    "rE": 2.43,
    "au": 0.121,
    "per": 21.784,
    "kind": "super-earth",
    "massE": 6.5,
    "tempK": 320
   },
   {
    "key": "d",
    "name": "GJ 887 d",
    "rE": 2.34,
    "au": 0.212,
    "per": 50.77,
    "kind": "super-earth",
    "massE": 6.1,
    "tempK": 241
   }
  ]
 },
 {
  "pack": "HD_110067",
  "star": "HD 110067",
  "ra": 12.6559,
  "dec": 20.0273,
  "ly": 104.887,
  "tempK": 5266,
  "spec": "K0.0 V",
  "rSun": 0.788,
  "col": 16771543,
  "pulsar": false,
  "kindStar": "orange K-type dwarf (main sequence)",
  "pbr": true,
  "planets": [
   {
    "key": "b",
    "name": "HD 110067 b",
    "rE": 2.2,
    "au": 0.0793,
    "per": 9.1137,
    "kind": "warm sub-neptune",
    "massE": 5.69,
    "tempK": 800
   },
   {
    "key": "c",
    "name": "HD 110067 c",
    "rE": 2.388,
    "au": 0.1039,
    "per": 13.6737,
    "kind": "warm sub-neptune",
    "massE": 6.3,
    "tempK": 699
   },
   {
    "key": "d",
    "name": "HD 110067 d",
    "rE": 2.852,
    "au": 0.1362,
    "per": 20.5196,
    "kind": "warm sub-neptune",
    "massE": 8.52,
    "tempK": 602
   },
   {
    "key": "e",
    "name": "HD 110067 e",
    "rE": 1.94,
    "au": 0.1785,
    "per": 30.7931,
    "kind": "warm sub-neptune",
    "massE": 3.9,
    "tempK": 533
   },
   {
    "key": "f",
    "name": "HD 110067 f",
    "rE": 2.601,
    "au": 0.2163,
    "per": 41.0585,
    "kind": "warm sub-neptune",
    "massE": 5.04,
    "tempK": 489
   },
   {
    "key": "g",
    "name": "HD 110067 g",
    "rE": 2.607,
    "au": 0.2621,
    "per": 54.7699,
    "kind": "warm sub-neptune",
    "massE": 8.4,
    "tempK": 440
   }
  ]
 },
 {
  "pack": "HD_189733",
  "star": "HD 189733",
  "ra": 20.0121,
  "dec": 22.7098,
  "ly": 64.461,
  "tempK": 5052,
  "spec": "K2 V",
  "rSun": 0.75,
  "col": 16770512,
  "pulsar": false,
  "kindStar": "orange K-type dwarf (main sequence)",
  "pbr": true,
  "planets": [
   {
    "key": "b",
    "name": "HD 189733 b",
    "rE": 12.666,
    "au": 0.03126,
    "per": 2.2186,
    "kind": "gas giant",
    "massE": 359.148,
    "tempK": 1209
   }
  ]
 },
 {
  "pack": "HD_209458",
  "star": "HD 209458",
  "ra": 22.053,
  "dec": 18.8842,
  "ly": 157.539,
  "tempK": 6091,
  "spec": "G0 V",
  "rSun": 1.19,
  "col": 16775407,
  "pulsar": false,
  "kindStar": "Sun-like G-type star (main sequence)",
  "pbr": true,
  "planets": [
   {
    "key": "b",
    "name": "HD 209458 b",
    "rE": 15.581,
    "au": 0.04707,
    "per": 3.5247,
    "kind": "gas giant",
    "massE": 232.016,
    "tempK": 1459
   }
  ]
 },
 {
  "pack": "HD_219134",
  "star": "HD 219134",
  "ra": 23.2225,
  "dec": 57.1696,
  "ly": 21.302,
  "tempK": 4699,
  "spec": "K3 V",
  "rSun": 0.778,
  "col": 16768707,
  "pulsar": false,
  "kindStar": "orange K-type dwarf (main sequence)",
  "pbr": true,
  "planets": [
   {
    "key": "b",
    "name": "HD 219134 b",
    "rE": 1.602,
    "au": 0.03876,
    "per": 3.0929,
    "kind": "hot rocky planet",
    "massE": 4.74,
    "tempK": 1015
   },
   {
    "key": "c",
    "name": "HD 219134 c",
    "rE": 1.511,
    "au": 0.0653,
    "per": 6.7646,
    "kind": "hot rocky planet",
    "massE": 4.36,
    "tempK": 782
   },
   {
    "key": "d",
    "name": "HD 219134 d",
    "rE": 1.61,
    "au": 0.237,
    "per": 46.859,
    "kind": "rocky terrestrial or super-earth candidate",
    "massE": 16.17,
    "tempK": 411
   },
   {
    "key": "h",
    "name": "HD 219134 h",
    "rE": 12.7,
    "au": 3.11,
    "per": 2247,
    "kind": "gas giant",
    "massE": 108.062,
    "tempK": 118
   }
  ]
 },
 {
  "pack": "HD_40307",
  "star": "HD 40307",
  "ra": 5.9011,
  "dec": -60.0237,
  "ly": 42.193,
  "tempK": 4956,
  "spec": "K2.5 V",
  "rSun": 0.717,
  "col": 16769996,
  "pulsar": false,
  "kindStar": "orange K-type dwarf (main sequence)",
  "pbr": true,
  "planets": [
   {
    "key": "b",
    "name": "HD 40307 b",
    "rE": 11.2,
    "au": 0.0468,
    "per": 4.3123,
    "kind": "gas giant",
    "massE": 1188.996,
    "tempK": 910
   },
   {
    "key": "c",
    "name": "HD 40307 c",
    "rE": 11.2,
    "au": 0.0799,
    "per": 9.6184,
    "kind": "gas giant",
    "massE": 1868.513,
    "tempK": 696
   },
   {
    "key": "d",
    "name": "HD 40307 d",
    "rE": 11.2,
    "au": 0.1321,
    "per": 20.432,
    "kind": "gas giant",
    "massE": 1775.389,
    "tempK": 541
   },
   {
    "key": "f",
    "name": "HD 40307 f",
    "rE": 2.13,
    "au": 0.247,
    "per": 51.76,
    "kind": "super-earth",
    "massE": 5.2,
    "tempK": 398
   }
  ]
 },
 {
  "pack": "HR_8799",
  "star": "HR 8799",
  "ra": 23.1247,
  "dec": 21.134,
  "ly": 134.52,
  "tempK": 7400,
  "spec": "A5 V",
  "rSun": 1.493,
  "col": 15265023,
  "pulsar": false,
  "kindStar": "white A-type star (main sequence)",
  "pbr": true,
  "planets": [
   {
    "key": "e",
    "name": "HR 8799 e",
    "rE": 13.115,
    "au": 16.4,
    "per": 20815.6,
    "kind": "gas giant",
    "massE": 3178.3,
    "tempK": 1150
   },
   {
    "key": "d",
    "name": "HR 8799 d",
    "rE": 13,
    "au": 24,
    "per": 37000,
    "kind": "gas giant",
    "massE": 3000,
    "tempK": 1300
   },
   {
    "key": "c",
    "name": "HR 8799 c",
    "rE": 13,
    "au": 38,
    "per": 69000,
    "kind": "gas giant",
    "massE": 3000,
    "tempK": 1200
   },
   {
    "key": "b",
    "name": "HR 8799 b",
    "rE": 13,
    "au": 68,
    "per": 170000,
    "kind": "gas giant",
    "massE": 2000,
    "tempK": 1200
   }
  ]
 },
 {
  "pack": "K2_138",
  "star": "K2-138",
  "ra": 23.2633,
  "dec": -10.8497,
  "ly": 660.744,
  "tempK": 5356,
  "spec": "G8 V",
  "rSun": 0.863,
  "col": 16772058,
  "pulsar": false,
  "kindStar": "Sun-like G-type star (main sequence)",
  "pbr": true,
  "planets": [
   {
    "key": "b",
    "name": "K2-138 b",
    "rE": 1.51,
    "au": 0.03385,
    "per": 2.3531,
    "kind": "hot rocky planet",
    "massE": 3.1,
    "tempK": 1157
   },
   {
    "key": "c",
    "name": "K2-138 c",
    "rE": 2.299,
    "au": 0.04461,
    "per": 3.56,
    "kind": "super-earth",
    "massE": 6.31,
    "tempK": 1012
   },
   {
    "key": "d",
    "name": "K2-138 d",
    "rE": 2.39,
    "au": 0.05893,
    "per": 5.4048,
    "kind": "super-earth",
    "massE": 7.92,
    "tempK": 888
   },
   {
    "key": "e",
    "name": "K2-138 e",
    "rE": 3.39,
    "au": 0.0782,
    "per": 8.2615,
    "kind": "super-earth",
    "massE": 12.97,
    "tempK": 757
   },
   {
    "key": "f",
    "name": "K2-138 f",
    "rE": 2.904,
    "au": 0.10447,
    "per": 12.7576,
    "kind": "super-earth",
    "massE": 1.63,
    "tempK": 653
   },
   {
    "key": "g",
    "name": "K2-138 g",
    "rE": 3.013,
    "au": 0.23109,
    "per": 41.968,
    "kind": "super-earth",
    "massE": 4.32,
    "tempK": 445
   }
  ]
 },
 {
  "pack": "K2_18",
  "star": "K2-18",
  "ra": 11.504,
  "dec": 7.5878,
  "ly": 124.026,
  "tempK": 3457,
  "spec": "M2.5 V",
  "rSun": 0.411,
  "col": 16760714,
  "pulsar": false,
  "kindStar": "red-dwarf star (main sequence)",
  "pbr": true,
  "planets": [
   {
    "key": "b",
    "name": "K2-18 b",
    "rE": 2.37,
    "au": 0.1429,
    "per": 32.9396,
    "kind": "super-earth",
    "massE": 8.92,
    "tempK": 284
   }
  ]
 },
 {
  "pack": "K2_72",
  "star": "K2-72",
  "ra": 22.3082,
  "dec": -9.612,
  "ly": 216.673,
  "tempK": 3360,
  "spec": "—",
  "rSun": 0.331,
  "col": 16759941,
  "pulsar": false,
  "kindStar": "red-dwarf star",
  "pbr": true,
  "planets": [
   {
    "key": "b",
    "name": "K2-72 b",
    "rE": 1.08,
    "au": 0.04,
    "per": 5.5772,
    "kind": "rocky terrestrial or super-earth candidate",
    "massE": 1.28,
    "tempK": 466
   },
   {
    "key": "d",
    "name": "K2-72 d",
    "rE": 1.01,
    "au": 0.05,
    "per": 7.7602,
    "kind": "rocky terrestrial or super-earth candidate",
    "massE": 1.01,
    "tempK": 417
   },
   {
    "key": "c",
    "name": "K2-72 c",
    "rE": 1.16,
    "au": 0.078,
    "per": 15.189,
    "kind": "rocky terrestrial or super-earth candidate",
    "massE": 1.65,
    "tempK": 334
   },
   {
    "key": "e",
    "name": "K2-72 e",
    "rE": 1.29,
    "au": 0.106,
    "per": 24.1589,
    "kind": "earth-size",
    "massE": 2.21,
    "tempK": 286
   }
  ]
 },
 {
  "pack": "Kepler_10",
  "star": "Kepler-10",
  "ra": 19.0453,
  "dec": 50.2415,
  "ly": 605.04,
  "tempK": 5708,
  "spec": "—",
  "rSun": 1.065,
  "col": 16773605,
  "pulsar": false,
  "kindStar": "Sun-like G-type star",
  "pbr": true,
  "planets": [
   {
    "key": "b",
    "name": "Kepler-10 b",
    "rE": 1.47,
    "au": 0.01685,
    "per": 0.8375,
    "kind": "hot rocky planet",
    "massE": 3.24,
    "tempK": 2188
   },
   {
    "key": "c",
    "name": "Kepler-10 c",
    "rE": 2.355,
    "au": 0.241,
    "per": 45.2943,
    "kind": "super-earth",
    "massE": 11.29,
    "tempK": 579
   },
   {
    "key": "d",
    "name": "Kepler-10 d",
    "rE": 3.49,
    "au": 0.5379,
    "per": 151.06,
    "kind": "super-earth",
    "massE": 12,
    "tempK": 387
   }
  ]
 },
 {
  "pack": "Kepler_11",
  "star": "Kepler-11",
  "ra": 19.8077,
  "dec": 41.9091,
  "ly": 2108.099,
  "tempK": 5663,
  "spec": "—",
  "rSun": 1.065,
  "col": 16773347,
  "pulsar": false,
  "kindStar": "Sun-like G-type star",
  "pbr": true,
  "planets": [
   {
    "key": "b",
    "name": "Kepler-11 b",
    "rE": 1.8,
    "au": 0.091,
    "per": 10.3039,
    "kind": "super-earth",
    "massE": 1.9,
    "tempK": 849
   },
   {
    "key": "c",
    "name": "Kepler-11 c",
    "rE": 2.87,
    "au": 0.107,
    "per": 13.0241,
    "kind": "super-earth",
    "massE": 2.9,
    "tempK": 786
   },
   {
    "key": "d",
    "name": "Kepler-11 d",
    "rE": 3.12,
    "au": 0.155,
    "per": 22.6845,
    "kind": "super-earth",
    "massE": 7.3,
    "tempK": 653
   },
   {
    "key": "e",
    "name": "Kepler-11 e",
    "rE": 4.19,
    "au": 0.195,
    "per": 31.9996,
    "kind": "super-earth",
    "massE": 8,
    "tempK": 582
   },
   {
    "key": "f",
    "name": "Kepler-11 f",
    "rE": 2.49,
    "au": 0.25,
    "per": 46.6888,
    "kind": "super-earth",
    "massE": 2,
    "tempK": 513
   },
   {
    "key": "g",
    "name": "Kepler-11 g",
    "rE": 3.33,
    "au": 0.466,
    "per": 118.3807,
    "kind": "super-earth",
    "massE": 25,
    "tempK": 376
   }
  ]
 },
 {
  "pack": "Kepler_138",
  "star": "Kepler-138",
  "ra": 19.3588,
  "dec": 43.2931,
  "ly": 218.076,
  "tempK": 3841,
  "spec": "M1 V",
  "rSun": 0.535,
  "col": 16763551,
  "pulsar": false,
  "kindStar": "red-dwarf star (main sequence)",
  "pbr": true,
  "planets": [
   {
    "key": "b",
    "name": "Kepler-138 b",
    "rE": 0.64,
    "au": 0.0753,
    "per": 10.3134,
    "kind": "rocky terrestrial or super-earth candidate",
    "massE": 0.07,
    "tempK": 452
   },
   {
    "key": "c",
    "name": "Kepler-138 c",
    "rE": 1.51,
    "au": 0.0913,
    "per": 13.7815,
    "kind": "likely water-rich super-earth",
    "massE": 2.3,
    "tempK": 410
   },
   {
    "key": "d",
    "name": "Kepler-138 d",
    "rE": 1.51,
    "au": 0.1288,
    "per": 23.0923,
    "kind": "likely water-rich super-earth",
    "massE": 2.1,
    "tempK": 345
   },
   {
    "key": "e",
    "name": "Kepler-138 e",
    "rE": 0.797,
    "au": 0.1803,
    "per": 38.23,
    "kind": "earth-size",
    "massE": 0.43,
    "tempK": 292
   }
  ]
 },
 {
  "pack": "Kepler_1649",
  "star": "Kepler-1649",
  "ra": 19.5002,
  "dec": 41.83,
  "ly": 300.688,
  "tempK": 3240,
  "spec": "—",
  "rSun": 0.232,
  "col": 16759166,
  "pulsar": false,
  "kindStar": "red-dwarf star",
  "pbr": true,
  "planets": [
   {
    "key": "b",
    "name": "Kepler-1649 b",
    "rE": 1.017,
    "au": 0.0514,
    "per": 8.6891,
    "kind": "inner warm rocky",
    "massE": 1.03,
    "tempK": 307
   },
   {
    "key": "c",
    "name": "Kepler-1649 c",
    "rE": 1.06,
    "au": 0.0649,
    "per": 19.5353,
    "kind": "earth-size habitable-zone rocky candidate",
    "massE": 1.2,
    "tempK": 234
   }
  ]
 },
 {
  "pack": "Kepler_16",
  "star": "Kepler-16",
  "ra": 19.2717,
  "dec": 51.7572,
  "ly": 244.895,
  "tempK": 4450,
  "spec": "—",
  "rSun": 0.649,
  "col": 16767161,
  "pulsar": false,
  "kindStar": "orange K-type dwarf",
  "pbr": true,
  "planets": [
   {
    "key": "b",
    "name": "Kepler-16 b",
    "rE": 8.449,
    "au": 0.7048,
    "per": 228.776,
    "kind": "gas giant",
    "massE": 105.833,
    "tempK": 206
   }
  ]
 },
 {
  "pack": "Kepler_186",
  "star": "Kepler-186",
  "ra": 19.9102,
  "dec": 43.955,
  "ly": 579.234,
  "tempK": 3788,
  "spec": "M1",
  "rSun": 0.472,
  "col": 16763036,
  "pulsar": false,
  "kindStar": "red-dwarf star",
  "pbr": true,
  "planets": [
   {
    "key": "b",
    "name": "Kepler-186 b",
    "rE": 1.07,
    "au": 0.0343,
    "per": 3.8868,
    "kind": "rocky terrestrial or super-earth candidate",
    "massE": 1.24,
    "tempK": 571
   },
   {
    "key": "c",
    "name": "Kepler-186 c",
    "rE": 1.25,
    "au": 0.0451,
    "per": 7.2673,
    "kind": "rocky terrestrial or super-earth candidate",
    "massE": 2.1,
    "tempK": 464
   },
   {
    "key": "d",
    "name": "Kepler-186 d",
    "rE": 1.4,
    "au": 0.0781,
    "per": 13.343,
    "kind": "rocky terrestrial or super-earth candidate",
    "massE": 2.54,
    "tempK": 379
   },
   {
    "key": "e",
    "name": "Kepler-186 e",
    "rE": 1.27,
    "au": 0.11,
    "per": 22.4077,
    "kind": "rocky terrestrial or super-earth candidate",
    "massE": 2.15,
    "tempK": 319
   },
   {
    "key": "f",
    "name": "Kepler-186 f",
    "rE": 1.17,
    "au": 0.356,
    "per": 129.9441,
    "kind": "earth-size habitable-zone rocky candidate",
    "massE": 1.7,
    "tempK": 188
   }
  ]
 },
 {
  "pack": "Kepler_20",
  "star": "Kepler-20",
  "ra": 19.1799,
  "dec": 42.3386,
  "ly": 921.597,
  "tempK": 5495,
  "spec": "—",
  "rSun": 0.916,
  "col": 16772574,
  "pulsar": false,
  "kindStar": "Sun-like G-type star",
  "pbr": true,
  "planets": [
   {
    "key": "b",
    "name": "Kepler-20 b",
    "rE": 1.773,
    "au": 0.04565,
    "per": 3.6961,
    "kind": "hot rocky planet",
    "massE": 9.7,
    "tempK": 1187
   },
   {
    "key": "e",
    "name": "Kepler-20 e",
    "rE": 0.821,
    "au": 0.0637,
    "per": 6.0985,
    "kind": "hot rocky planet",
    "massE": 0.76,
    "tempK": 1004
   },
   {
    "key": "c",
    "name": "Kepler-20 c",
    "rE": 2.894,
    "au": 0.0936,
    "per": 10.8541,
    "kind": "super-earth",
    "massE": 11.1,
    "tempK": 828
   },
   {
    "key": "f",
    "name": "Kepler-20 f",
    "rE": 0.952,
    "au": 0.1387,
    "per": 19.5783,
    "kind": "hot rocky planet",
    "massE": 1.4,
    "tempK": 681
   },
   {
    "key": "g",
    "name": "Kepler-20 g",
    "rE": 4.71,
    "au": 0.2055,
    "per": 34.94,
    "kind": "super-earth",
    "massE": 19.96,
    "tempK": 524
   },
   {
    "key": "d",
    "name": "Kepler-20 d",
    "rE": 2.606,
    "au": 0.3474,
    "per": 77.6115,
    "kind": "super-earth",
    "massE": 13.4,
    "tempK": 430
   }
  ]
 },
 {
  "pack": "Kepler_22",
  "star": "Kepler-22",
  "ra": 19.2811,
  "dec": 47.8841,
  "ly": 634.837,
  "tempK": 5596,
  "spec": "G5 V",
  "rSun": 0.869,
  "col": 16773089,
  "pulsar": false,
  "kindStar": "Sun-like G-type star (main sequence)",
  "pbr": true,
  "planets": [
   {
    "key": "b",
    "name": "Kepler-22 b",
    "rE": 2.1,
    "au": 0.812,
    "per": 289.8639,
    "kind": "super-earth",
    "massE": 9.1,
    "tempK": 279
   }
  ]
 },
 {
  "pack": "Kepler_296",
  "star": "Kepler-296",
  "ra": 19.1027,
  "dec": 49.4373,
  "ly": 544.681,
  "tempK": 3740,
  "spec": "M2 V",
  "rSun": 0.48,
  "col": 16762778,
  "pulsar": false,
  "kindStar": "red-dwarf star (main sequence)",
  "pbr": true,
  "planets": [
   {
    "key": "c",
    "name": "Kepler-296 c",
    "rE": 2,
    "au": 0.0521,
    "per": 5.8416,
    "kind": "super-earth",
    "massE": 4.66,
    "tempK": 606
   },
   {
    "key": "b",
    "name": "Kepler-296 b",
    "rE": 1.61,
    "au": 0.079,
    "per": 10.8644,
    "kind": "rocky terrestrial or super-earth candidate",
    "massE": 3.22,
    "tempK": 495
   },
   {
    "key": "d",
    "name": "Kepler-296 d",
    "rE": 2.09,
    "au": 0.118,
    "per": 19.8503,
    "kind": "super-earth",
    "massE": 5.02,
    "tempK": 403
   },
   {
    "key": "e",
    "name": "Kepler-296 e",
    "rE": 1.53,
    "au": 0.169,
    "per": 34.1421,
    "kind": "rocky terrestrial or super-earth candidate",
    "massE": 2.96,
    "tempK": 337
   },
   {
    "key": "f",
    "name": "Kepler-296 f",
    "rE": 1.8,
    "au": 0.255,
    "per": 63.3363,
    "kind": "super-earth",
    "massE": 3.89,
    "tempK": 274
   }
  ]
 },
 {
  "pack": "Kepler_37",
  "star": "Kepler-37",
  "ra": 18.9373,
  "dec": 44.5184,
  "ly": 208.481,
  "tempK": 5357,
  "spec": "—",
  "rSun": 0.789,
  "col": 16772058,
  "pulsar": false,
  "kindStar": "Sun-like G-type star",
  "pbr": true,
  "planets": [
   {
    "key": "b",
    "name": "Kepler-37 b",
    "rE": 0.31,
    "au": 0.1019,
    "per": 13.367,
    "kind": "hot rocky planet",
    "massE": 0.79,
    "tempK": 718
   },
   {
    "key": "c",
    "name": "Kepler-37 c",
    "rE": 0.755,
    "au": 0.139,
    "per": 21.3018,
    "kind": "rocky terrestrial or super-earth candidate",
    "massE": 1.3,
    "tempK": 615
   },
   {
    "key": "d",
    "name": "Kepler-37 d",
    "rE": 2.03,
    "au": 0.2109,
    "per": 39.7923,
    "kind": "super-earth",
    "massE": 2,
    "tempK": 499
   },
   {
    "key": "e",
    "name": "Kepler-37 e",
    "rE": 0.37,
    "au": 0.25,
    "per": 51.196,
    "kind": "uncertain compact rocky candidate (visual assumption follows pack geometry)",
    "massE": 8.1,
    "tempK": 401
   }
  ]
 },
 {
  "pack": "Kepler_442",
  "star": "Kepler-442",
  "ra": 19.0244,
  "dec": 39.2801,
  "ly": 1193.618,
  "tempK": 4402,
  "spec": "—",
  "rSun": 0.598,
  "col": 16766904,
  "pulsar": false,
  "kindStar": "orange K-type dwarf",
  "pbr": true,
  "planets": [
   {
    "key": "b",
    "name": "Kepler-442 b",
    "rE": 1.34,
    "au": 0.409,
    "per": 112.3053,
    "kind": "earth-size",
    "massE": 2.36,
    "tempK": 241
   }
  ]
 },
 {
  "pack": "Kepler_444",
  "star": "Kepler-444",
  "ra": 19.3169,
  "dec": 41.6319,
  "ly": 118.85,
  "tempK": 5046,
  "spec": "K",
  "rSun": 0.752,
  "col": 16770512,
  "pulsar": false,
  "kindStar": "orange K-type dwarf",
  "pbr": true,
  "planets": [
   {
    "key": "b",
    "name": "Kepler-444 b",
    "rE": 0.403,
    "au": 0.04178,
    "per": 3.6001,
    "kind": "hot rocky planet",
    "massE": 0.037,
    "tempK": 938
   },
   {
    "key": "c",
    "name": "Kepler-444 c",
    "rE": 0.497,
    "au": 0.04881,
    "per": 4.5459,
    "kind": "hot rocky planet",
    "massE": 0.079,
    "tempK": 868
   },
   {
    "key": "d",
    "name": "Kepler-444 d",
    "rE": 0.53,
    "au": 0.06,
    "per": 6.1894,
    "kind": "hot rocky planet",
    "massE": 0.2,
    "tempK": 783
   },
   {
    "key": "e",
    "name": "Kepler-444 e",
    "rE": 0.546,
    "au": 0.0696,
    "per": 7.7435,
    "kind": "hot rocky planet",
    "massE": 0.1,
    "tempK": 727
   },
   {
    "key": "f",
    "name": "Kepler-444 f",
    "rE": 0.741,
    "au": 0.0811,
    "per": 9.7405,
    "kind": "hot rocky planet",
    "massE": 0.332,
    "tempK": 673
   }
  ]
 }
];
export default EXO_SYSTEMS;
